export const INTERNAL_API_ENDPOINTS = {
  catalogPage: "/api/catalog/page",
  catalogProducts: "/api/catalog/products",
  catalogCategories: "/api/catalog/categories",
  catalogSubcategories: "/api/catalog/subcategories",
  siteHome: "/api/site/home",
  siteAbout: "/api/site/about",
  support: "/api/support",
  supportFaq: "/api/support/faq",
  adminDashboard: "/api/admin/dashboard",
  adminUsers: "/api/admin/users",
  adminBanners: "/api/admin/banners",
  adminLibrary: "/api/admin/library",
  adminMessages: "/api/admin/messages",
  adminAudit: "/api/admin/audit",
  adminConfig: "/api/admin/config",
  cmsProducts: "/api/cms/products",
  authLogin: "/api/auth/login",
  authRefresh: "/api/auth/refresh",
  authLogout: "/api/auth/logout",
  upload: "/api/upload",
  uploadComplete: "/api/upload/complete",
} as const;
