/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  GetApiTemplatesParams,
  PatchApiTemplatesIdBody,
  PostApiTemplatesBody,
  Template,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List attribute templates
 */
export const getApiTemplates = (
  params?: GetApiTemplatesParams,
  signal?: AbortSignal,
) => {
  return orvalClient<Template[]>({
    url: `/api/templates`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiTemplatesQueryKey = (params?: GetApiTemplatesParams) => {
  return [`/api/templates`, ...(params ? [params] : [])] as const;
};

export const getGetApiTemplatesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiTemplates>>,
  TError = unknown,
>(
  params?: GetApiTemplatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTemplates>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiTemplatesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTemplates>>> = ({
    signal,
  }) => getApiTemplates(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiTemplatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiTemplates>>
>;
export type GetApiTemplatesQueryError = unknown;

export function useGetApiTemplates<
  TData = Awaited<ReturnType<typeof getApiTemplates>>,
  TError = unknown,
>(
  params: undefined | GetApiTemplatesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTemplates>>,
          TError,
          Awaited<ReturnType<typeof getApiTemplates>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTemplates<
  TData = Awaited<ReturnType<typeof getApiTemplates>>,
  TError = unknown,
>(
  params?: GetApiTemplatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTemplates>>,
          TError,
          Awaited<ReturnType<typeof getApiTemplates>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTemplates<
  TData = Awaited<ReturnType<typeof getApiTemplates>>,
  TError = unknown,
>(
  params?: GetApiTemplatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List attribute templates
 */

export function useGetApiTemplates<
  TData = Awaited<ReturnType<typeof getApiTemplates>>,
  TError = unknown,
>(
  params?: GetApiTemplatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiTemplatesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create attribute template
 */
export const postApiTemplates = (
  postApiTemplatesBody: PostApiTemplatesBody,
  signal?: AbortSignal,
) => {
  return orvalClient<Template>({
    url: `/api/templates`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiTemplatesBody,
    signal,
  });
};

export const getPostApiTemplatesQueryKey = (
  postApiTemplatesBody?: PostApiTemplatesBody,
) => {
  return ["POST", `/api/templates`, postApiTemplatesBody] as const;
};

export const getPostApiTemplatesQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiTemplates>>,
  TError = unknown,
>(
  postApiTemplatesBody: PostApiTemplatesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiTemplates>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPostApiTemplatesQueryKey(postApiTemplatesBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiTemplates>>
  > = ({ signal }) => postApiTemplates(postApiTemplatesBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiTemplatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiTemplates>>
>;
export type PostApiTemplatesQueryError = unknown;

export function usePostApiTemplates<
  TData = Awaited<ReturnType<typeof postApiTemplates>>,
  TError = unknown,
>(
  postApiTemplatesBody: PostApiTemplatesBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiTemplates>>,
          TError,
          Awaited<ReturnType<typeof postApiTemplates>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiTemplates<
  TData = Awaited<ReturnType<typeof postApiTemplates>>,
  TError = unknown,
>(
  postApiTemplatesBody: PostApiTemplatesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiTemplates>>,
          TError,
          Awaited<ReturnType<typeof postApiTemplates>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiTemplates<
  TData = Awaited<ReturnType<typeof postApiTemplates>>,
  TError = unknown,
>(
  postApiTemplatesBody: PostApiTemplatesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Create attribute template
 */

export function usePostApiTemplates<
  TData = Awaited<ReturnType<typeof postApiTemplates>>,
  TError = unknown,
>(
  postApiTemplatesBody: PostApiTemplatesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiTemplatesQueryOptions(
    postApiTemplatesBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update template
 */
export const patchApiTemplatesId = (
  id: string,
  patchApiTemplatesIdBody: PatchApiTemplatesIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<Template>({
    url: `/api/templates/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiTemplatesIdBody,
    signal,
  });
};

export const getPatchApiTemplatesIdQueryKey = (
  id: string,
  patchApiTemplatesIdBody?: PatchApiTemplatesIdBody,
) => {
  return ["PATCH", `/api/templates/${id}`, patchApiTemplatesIdBody] as const;
};

export const getPatchApiTemplatesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiTemplatesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiTemplatesIdBody: PatchApiTemplatesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiTemplatesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiTemplatesIdQueryKey(id, patchApiTemplatesIdBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiTemplatesId>>
  > = ({ signal }) => patchApiTemplatesId(id, patchApiTemplatesIdBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiTemplatesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiTemplatesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiTemplatesId>>
>;
export type PatchApiTemplatesIdQueryError = ApiErrorPayload;

export function usePatchApiTemplatesId<
  TData = Awaited<ReturnType<typeof patchApiTemplatesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiTemplatesIdBody: PatchApiTemplatesIdBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiTemplatesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiTemplatesId>>,
          TError,
          Awaited<ReturnType<typeof patchApiTemplatesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiTemplatesId<
  TData = Awaited<ReturnType<typeof patchApiTemplatesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiTemplatesIdBody: PatchApiTemplatesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiTemplatesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiTemplatesId>>,
          TError,
          Awaited<ReturnType<typeof patchApiTemplatesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiTemplatesId<
  TData = Awaited<ReturnType<typeof patchApiTemplatesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiTemplatesIdBody: PatchApiTemplatesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiTemplatesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update template
 */

export function usePatchApiTemplatesId<
  TData = Awaited<ReturnType<typeof patchApiTemplatesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiTemplatesIdBody: PatchApiTemplatesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiTemplatesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiTemplatesIdQueryOptions(
    id,
    patchApiTemplatesIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete template
 */
export const deleteApiTemplatesId = (id: string, signal?: AbortSignal) => {
  return orvalClient<unknown>({
    url: `/api/templates/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiTemplatesIdQueryKey = (id: string) => {
  return ["DELETE", `/api/templates/${id}`] as const;
};

export const getDeleteApiTemplatesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiTemplatesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiTemplatesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDeleteApiTemplatesIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiTemplatesId>>
  > = ({ signal }) => deleteApiTemplatesId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiTemplatesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiTemplatesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiTemplatesId>>
>;
export type DeleteApiTemplatesIdQueryError = ApiErrorPayload;

export function useDeleteApiTemplatesId<
  TData = Awaited<ReturnType<typeof deleteApiTemplatesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiTemplatesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiTemplatesId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiTemplatesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiTemplatesId<
  TData = Awaited<ReturnType<typeof deleteApiTemplatesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiTemplatesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiTemplatesId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiTemplatesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiTemplatesId<
  TData = Awaited<ReturnType<typeof deleteApiTemplatesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiTemplatesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Delete template
 */

export function useDeleteApiTemplatesId<
  TData = Awaited<ReturnType<typeof deleteApiTemplatesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiTemplatesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiTemplatesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
