/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { ContactSubmitResponse } from "../../model/contactSubmitResponse";

import type { PostApiContactBody } from "../../model/postApiContactBody";

import type { PublicDepartmentItem } from "../../model/publicDepartmentItem";

import { serverOrvalClient } from "../../orval-server";

/**
 * @summary List contact form departments
 */
export const getApiContactDepartments = () => {
  return serverOrvalClient<PublicDepartmentItem[]>({
    url: `/api/contact/departments`,
    method: "GET",
  });
};
/**
 * @summary Submit contact
 */
export const postApiContact = (postApiContactBody: PostApiContactBody) => {
  return serverOrvalClient<ContactSubmitResponse>({
    url: `/api/contact`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiContactBody,
  });
};
export type GetApiContactDepartmentsResult = NonNullable<
  Awaited<ReturnType<typeof getApiContactDepartments>>
>;
export type PostApiContactResult = NonNullable<
  Awaited<ReturnType<typeof postApiContact>>
>;
