import { defineConfig } from "orval";
import dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const apiBase = process.env.CMS_API_BASE_URL ?? "http://localhost:3333";

export default defineConfig({
  stetsom: {
    input: {
      target: `${apiBase}/docs/json`,
    },
    output: {
      // Splits generated files by OpenAPI tag (Products, Banners, Pages, etc.)
      mode: "tags-split",
      target: "./src/api/stetsom/endpoints",
      schemas: "./src/api/stetsom/model",
      client: "react-query",
      // axios → mutator receives a single AxiosRequestConfig object
      httpClient: "axios",
      // Custom mutator: handles server-side (direct) vs client-side (BFF proxy)
      override: {
        mutator: {
          path: "./src/api/stetsom/orval-client.ts",
          name: "orvalClient",
        },
        query: {
          useQuery: true,
          useMutation: true,
          signal: true,
        },
      },
    },
    hooks: {
      afterAllFilesWrite: "prettier --write ./src/api/stetsom",
    },
  },
  // Server target: plain typed functions (no hooks) for RSC / Server Actions.
  // Reuses serverOrvalClient as the mutator (direct call + cookie + mock), so
  // the error contract stays identical. Generated into ./server, imported ONLY
  // by server code — never re-exported by the client barrel (next/headers).
  stetsomServer: {
    input: {
      target: `${apiBase}/docs/json`,
      // Only the tags RSC actually fetches. Exact tag strings from /docs/json.
      filters: {
        mode: "include",
        tags: [
          "Products",
          "Products Public",
          "Categories Public",
          "Pages Public",
          "Banners Public",
          "Partner Locations Public",
          "Contact",
        ],
      },
    },
    output: {
      mode: "tags-split",
      client: "axios-functions",
      httpClient: "axios",
      target: "./src/api/stetsom/server",
      // Reuse the models generated by the `stetsom` target — same type identity.
      schemas: "./src/api/stetsom/model",
      // Do NOT regenerate index barrels: the `stetsom` target owns the full
      // model/index.ts. Without this, the filtered server target overwrites it
      // with only its subset, breaking every other model import.
      indexFiles: false,
      override: {
        mutator: {
          path: "./src/api/stetsom/orval-server.ts",
          name: "serverOrvalClient",
        },
      },
    },
    hooks: {
      afterAllFilesWrite: "prettier --write ./src/api/stetsom",
    },
  },
});
