/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { GetApiRepresentativesParams, Representative } from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List representatives
 */
export const getApiRepresentatives = (
  params?: GetApiRepresentativesParams,
  signal?: AbortSignal,
) => {
  return orvalClient<Representative[]>({
    url: `/api/representatives`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiRepresentativesQueryKey = (
  params?: GetApiRepresentativesParams,
) => {
  return [`/api/representatives`, ...(params ? [params] : [])] as const;
};

export const getGetApiRepresentativesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiRepresentatives>>,
  TError = unknown,
>(
  params?: GetApiRepresentativesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiRepresentatives>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiRepresentativesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiRepresentatives>>
  > = ({ signal }) => getApiRepresentatives(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiRepresentatives>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiRepresentativesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiRepresentatives>>
>;
export type GetApiRepresentativesQueryError = unknown;

export function useGetApiRepresentatives<
  TData = Awaited<ReturnType<typeof getApiRepresentatives>>,
  TError = unknown,
>(
  params: undefined | GetApiRepresentativesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiRepresentatives>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiRepresentatives>>,
          TError,
          Awaited<ReturnType<typeof getApiRepresentatives>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiRepresentatives<
  TData = Awaited<ReturnType<typeof getApiRepresentatives>>,
  TError = unknown,
>(
  params?: GetApiRepresentativesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiRepresentatives>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiRepresentatives>>,
          TError,
          Awaited<ReturnType<typeof getApiRepresentatives>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiRepresentatives<
  TData = Awaited<ReturnType<typeof getApiRepresentatives>>,
  TError = unknown,
>(
  params?: GetApiRepresentativesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiRepresentatives>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List representatives
 */

export function useGetApiRepresentatives<
  TData = Awaited<ReturnType<typeof getApiRepresentatives>>,
  TError = unknown,
>(
  params?: GetApiRepresentativesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiRepresentatives>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiRepresentativesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
