/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  GetApiPagesSlug200,
  GetApiPagesSlugParams,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary Get page
 */
export const getApiPagesSlug = (
  slug: string,
  params?: GetApiPagesSlugParams,
  signal?: AbortSignal,
) => {
  return orvalClient<GetApiPagesSlug200>({
    url: `/api/pages/${slug}`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiPagesSlugQueryKey = (
  slug: string,
  params?: GetApiPagesSlugParams,
) => {
  return [`/api/pages/${slug}`, ...(params ? [params] : [])] as const;
};

export const getGetApiPagesSlugQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPagesSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiPagesSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPagesSlug>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiPagesSlugQueryKey(slug, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPagesSlug>>> = ({
    signal,
  }) => getApiPagesSlug(slug, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: slug !== null && slug !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPagesSlug>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPagesSlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPagesSlug>>
>;
export type GetApiPagesSlugQueryError = ApiErrorPayload;

export function useGetApiPagesSlug<
  TData = Awaited<ReturnType<typeof getApiPagesSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params: undefined | GetApiPagesSlugParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPagesSlug>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPagesSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiPagesSlug>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPagesSlug<
  TData = Awaited<ReturnType<typeof getApiPagesSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiPagesSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPagesSlug>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPagesSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiPagesSlug>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPagesSlug<
  TData = Awaited<ReturnType<typeof getApiPagesSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiPagesSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPagesSlug>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get page
 */

export function useGetApiPagesSlug<
  TData = Awaited<ReturnType<typeof getApiPagesSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiPagesSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPagesSlug>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPagesSlugQueryOptions(slug, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
