/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  BannerWithUploads,
  BannersPayload,
  GetApiBannersParams,
  PatchApiBannersIdBody,
  PostApiBannersBody,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List banners
 */
export const getApiBanners = (
  params?: GetApiBannersParams,
  signal?: AbortSignal,
) => {
  return orvalClient<BannersPayload>({
    url: `/api/banners`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiBannersQueryKey = (params?: GetApiBannersParams) => {
  return [`/api/banners`, ...(params ? [params] : [])] as const;
};

export const getGetApiBannersQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiBanners>>,
  TError = unknown,
>(
  params?: GetApiBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiBanners>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiBannersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBanners>>> = ({
    signal,
  }) => getApiBanners(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiBanners>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiBannersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiBanners>>
>;
export type GetApiBannersQueryError = unknown;

export function useGetApiBanners<
  TData = Awaited<ReturnType<typeof getApiBanners>>,
  TError = unknown,
>(
  params: undefined | GetApiBannersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiBanners>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBanners>>,
          TError,
          Awaited<ReturnType<typeof getApiBanners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBanners<
  TData = Awaited<ReturnType<typeof getApiBanners>>,
  TError = unknown,
>(
  params?: GetApiBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiBanners>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBanners>>,
          TError,
          Awaited<ReturnType<typeof getApiBanners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBanners<
  TData = Awaited<ReturnType<typeof getApiBanners>>,
  TError = unknown,
>(
  params?: GetApiBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiBanners>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List banners
 */

export function useGetApiBanners<
  TData = Awaited<ReturnType<typeof getApiBanners>>,
  TError = unknown,
>(
  params?: GetApiBannersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiBanners>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiBannersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns the banner and presigned upload URLs. PUT the file(s) to uploads.desktop.uploadUrl.
 * @summary Create banner
 */
export const postApiBanners = (
  postApiBannersBody: PostApiBannersBody,
  signal?: AbortSignal,
) => {
  return orvalClient<BannerWithUploads>({
    url: `/api/banners`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiBannersBody,
    signal,
  });
};

export const getPostApiBannersQueryKey = (
  postApiBannersBody?: PostApiBannersBody,
) => {
  return ["POST", `/api/banners`, postApiBannersBody] as const;
};

export const getPostApiBannersQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiBanners>>,
  TError = ApiErrorPayload,
>(
  postApiBannersBody: PostApiBannersBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiBanners>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPostApiBannersQueryKey(postApiBannersBody);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiBanners>>> = ({
    signal,
  }) => postApiBanners(postApiBannersBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiBanners>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiBannersQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiBanners>>
>;
export type PostApiBannersQueryError = ApiErrorPayload;

export function usePostApiBanners<
  TData = Awaited<ReturnType<typeof postApiBanners>>,
  TError = ApiErrorPayload,
>(
  postApiBannersBody: PostApiBannersBody,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiBanners>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiBanners>>,
          TError,
          Awaited<ReturnType<typeof postApiBanners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiBanners<
  TData = Awaited<ReturnType<typeof postApiBanners>>,
  TError = ApiErrorPayload,
>(
  postApiBannersBody: PostApiBannersBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiBanners>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiBanners>>,
          TError,
          Awaited<ReturnType<typeof postApiBanners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiBanners<
  TData = Awaited<ReturnType<typeof postApiBanners>>,
  TError = ApiErrorPayload,
>(
  postApiBannersBody: PostApiBannersBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiBanners>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Create banner
 */

export function usePostApiBanners<
  TData = Awaited<ReturnType<typeof postApiBanners>>,
  TError = ApiErrorPayload,
>(
  postApiBannersBody: PostApiBannersBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiBanners>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiBannersQueryOptions(
    postApiBannersBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update banner
 */
export const patchApiBannersId = (
  id: string,
  patchApiBannersIdBody: PatchApiBannersIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<BannerWithUploads>({
    url: `/api/banners/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiBannersIdBody,
    signal,
  });
};

export const getPatchApiBannersIdQueryKey = (
  id: string,
  patchApiBannersIdBody?: PatchApiBannersIdBody,
) => {
  return ["PATCH", `/api/banners/${id}`, patchApiBannersIdBody] as const;
};

export const getPatchApiBannersIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiBannersId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiBannersIdBody: PatchApiBannersIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiBannersId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiBannersIdQueryKey(id, patchApiBannersIdBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiBannersId>>
  > = ({ signal }) => patchApiBannersId(id, patchApiBannersIdBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiBannersId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiBannersIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiBannersId>>
>;
export type PatchApiBannersIdQueryError = ApiErrorPayload;

export function usePatchApiBannersId<
  TData = Awaited<ReturnType<typeof patchApiBannersId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiBannersIdBody: PatchApiBannersIdBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiBannersId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiBannersId>>,
          TError,
          Awaited<ReturnType<typeof patchApiBannersId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiBannersId<
  TData = Awaited<ReturnType<typeof patchApiBannersId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiBannersIdBody: PatchApiBannersIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiBannersId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiBannersId>>,
          TError,
          Awaited<ReturnType<typeof patchApiBannersId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiBannersId<
  TData = Awaited<ReturnType<typeof patchApiBannersId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiBannersIdBody: PatchApiBannersIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiBannersId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update banner
 */

export function usePatchApiBannersId<
  TData = Awaited<ReturnType<typeof patchApiBannersId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiBannersIdBody: PatchApiBannersIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiBannersId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiBannersIdQueryOptions(
    id,
    patchApiBannersIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete banner
 */
export const deleteApiBannersId = (id: string, signal?: AbortSignal) => {
  return orvalClient<unknown>({
    url: `/api/banners/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiBannersIdQueryKey = (id: string) => {
  return ["DELETE", `/api/banners/${id}`] as const;
};

export const getDeleteApiBannersIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiBannersId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiBannersId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDeleteApiBannersIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiBannersId>>
  > = ({ signal }) => deleteApiBannersId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiBannersId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiBannersIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiBannersId>>
>;
export type DeleteApiBannersIdQueryError = ApiErrorPayload;

export function useDeleteApiBannersId<
  TData = Awaited<ReturnType<typeof deleteApiBannersId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiBannersId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiBannersId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiBannersId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiBannersId<
  TData = Awaited<ReturnType<typeof deleteApiBannersId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiBannersId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiBannersId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiBannersId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiBannersId<
  TData = Awaited<ReturnType<typeof deleteApiBannersId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiBannersId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Delete banner
 */

export function useDeleteApiBannersId<
  TData = Awaited<ReturnType<typeof deleteApiBannersId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiBannersId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiBannersIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
