/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetApiBannersActiveParams,
  HeroBannerSlidesPayload,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List active banners
 */
export const getApiBannersActive = (
  params?: GetApiBannersActiveParams,
  signal?: AbortSignal,
) => {
  return orvalClient<HeroBannerSlidesPayload>({
    url: `/api/banners/active`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiBannersActiveQueryKey = (
  params?: GetApiBannersActiveParams,
) => {
  return [`/api/banners/active`, ...(params ? [params] : [])] as const;
};

export const getGetApiBannersActiveQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiBannersActive>>,
  TError = unknown,
>(
  params?: GetApiBannersActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBannersActive>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiBannersActiveQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiBannersActive>>
  > = ({ signal }) => getApiBannersActive(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiBannersActive>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiBannersActiveQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiBannersActive>>
>;
export type GetApiBannersActiveQueryError = unknown;

export function useGetApiBannersActive<
  TData = Awaited<ReturnType<typeof getApiBannersActive>>,
  TError = unknown,
>(
  params: undefined | GetApiBannersActiveParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBannersActive>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBannersActive>>,
          TError,
          Awaited<ReturnType<typeof getApiBannersActive>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBannersActive<
  TData = Awaited<ReturnType<typeof getApiBannersActive>>,
  TError = unknown,
>(
  params?: GetApiBannersActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBannersActive>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBannersActive>>,
          TError,
          Awaited<ReturnType<typeof getApiBannersActive>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBannersActive<
  TData = Awaited<ReturnType<typeof getApiBannersActive>>,
  TError = unknown,
>(
  params?: GetApiBannersActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBannersActive>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List active banners
 */

export function useGetApiBannersActive<
  TData = Awaited<ReturnType<typeof getApiBannersActive>>,
  TError = unknown,
>(
  params?: GetApiBannersActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBannersActive>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiBannersActiveQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
