/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetApiTechnicalAssistancesParams,
  TechnicalAssistance,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List service centers
 */
export const getApiTechnicalAssistances = (
  params?: GetApiTechnicalAssistancesParams,
  signal?: AbortSignal,
) => {
  return orvalClient<TechnicalAssistance[]>({
    url: `/api/technical-assistances`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiTechnicalAssistancesQueryKey = (
  params?: GetApiTechnicalAssistancesParams,
) => {
  return [`/api/technical-assistances`, ...(params ? [params] : [])] as const;
};

export const getGetApiTechnicalAssistancesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
  TError = unknown,
>(
  params?: GetApiTechnicalAssistancesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiTechnicalAssistancesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiTechnicalAssistances>>
  > = ({ signal }) => getApiTechnicalAssistances(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiTechnicalAssistancesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiTechnicalAssistances>>
>;
export type GetApiTechnicalAssistancesQueryError = unknown;

export function useGetApiTechnicalAssistances<
  TData = Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
  TError = unknown,
>(
  params: undefined | GetApiTechnicalAssistancesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
          TError,
          Awaited<ReturnType<typeof getApiTechnicalAssistances>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTechnicalAssistances<
  TData = Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
  TError = unknown,
>(
  params?: GetApiTechnicalAssistancesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
          TError,
          Awaited<ReturnType<typeof getApiTechnicalAssistances>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTechnicalAssistances<
  TData = Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
  TError = unknown,
>(
  params?: GetApiTechnicalAssistancesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List service centers
 */

export function useGetApiTechnicalAssistances<
  TData = Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
  TError = unknown,
>(
  params?: GetApiTechnicalAssistancesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTechnicalAssistances>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiTechnicalAssistancesQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
