/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCategoriesParams } from "../../model/getApiCategoriesParams";

import type { PublicCategory } from "../../model/publicCategory";

import { serverOrvalClient } from "../../orval-server";

/**
 * @summary List categories
 */
export const getApiCategories = (params?: GetApiCategoriesParams) => {
  return serverOrvalClient<PublicCategory[]>({
    url: `/api/categories`,
    method: "GET",
    params,
  });
};
export type GetApiCategoriesResult = NonNullable<
  Awaited<ReturnType<typeof getApiCategories>>
>;
