/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  ContactMessagesPayload,
  GetApiMessagesParams,
  PatchApiMessagesId200,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List contact form messages
 */
export const getApiMessages = (
  params?: GetApiMessagesParams,
  signal?: AbortSignal,
) => {
  return orvalClient<ContactMessagesPayload>({
    url: `/api/messages/`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiMessagesQueryKey = (params?: GetApiMessagesParams) => {
  return [`/api/messages/`, ...(params ? [params] : [])] as const;
};

export const getGetApiMessagesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMessages>>,
  TError = unknown,
>(
  params?: GetApiMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMessages>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiMessagesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMessages>>> = ({
    signal,
  }) => getApiMessages(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiMessages>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiMessagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiMessages>>
>;
export type GetApiMessagesQueryError = unknown;

export function useGetApiMessages<
  TData = Awaited<ReturnType<typeof getApiMessages>>,
  TError = unknown,
>(
  params: undefined | GetApiMessagesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMessages>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMessages>>,
          TError,
          Awaited<ReturnType<typeof getApiMessages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMessages<
  TData = Awaited<ReturnType<typeof getApiMessages>>,
  TError = unknown,
>(
  params?: GetApiMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMessages>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMessages>>,
          TError,
          Awaited<ReturnType<typeof getApiMessages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMessages<
  TData = Awaited<ReturnType<typeof getApiMessages>>,
  TError = unknown,
>(
  params?: GetApiMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMessages>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List contact form messages
 */

export function useGetApiMessages<
  TData = Awaited<ReturnType<typeof getApiMessages>>,
  TError = unknown,
>(
  params?: GetApiMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMessages>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiMessagesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Mark message as read
 */
export const patchApiMessagesId = (id: string, signal?: AbortSignal) => {
  return orvalClient<PatchApiMessagesId200>({
    url: `/api/messages/${id}`,
    method: "PATCH",
    signal,
  });
};

export const getPatchApiMessagesIdQueryKey = (id: string) => {
  return ["PATCH", `/api/messages/${id}`] as const;
};

export const getPatchApiMessagesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiMessagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiMessagesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPatchApiMessagesIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiMessagesId>>
  > = ({ signal }) => patchApiMessagesId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiMessagesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiMessagesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiMessagesId>>
>;
export type PatchApiMessagesIdQueryError = ApiErrorPayload;

export function usePatchApiMessagesId<
  TData = Awaited<ReturnType<typeof patchApiMessagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiMessagesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiMessagesId>>,
          TError,
          Awaited<ReturnType<typeof patchApiMessagesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiMessagesId<
  TData = Awaited<ReturnType<typeof patchApiMessagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiMessagesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiMessagesId>>,
          TError,
          Awaited<ReturnType<typeof patchApiMessagesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiMessagesId<
  TData = Awaited<ReturnType<typeof patchApiMessagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiMessagesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Mark message as read
 */

export function usePatchApiMessagesId<
  TData = Awaited<ReturnType<typeof patchApiMessagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiMessagesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiMessagesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
