/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiConfigPublicParams } from "../../model/getApiConfigPublicParams";

import type { PublicConfig } from "../../model/publicConfig";

import { serverOrvalClient } from "../../orval-server";

/**
 * Locale-resolved, non-sensitive subset of CmsConfig for the public site (contact info, logo URLs, and social links).
 * @summary Get public config
 */
export const getApiConfigPublic = (params?: GetApiConfigPublicParams) => {
  return serverOrvalClient<PublicConfig>({
    url: `/api/config/public`,
    method: "GET",
    params,
  });
};
export type GetApiConfigPublicResult = NonNullable<
  Awaited<ReturnType<typeof getApiConfigPublic>>
>;
