/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AuditPayload, GetApiAuditParams } from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List audit entries
 */
export const getApiAudit = (
  params?: GetApiAuditParams,
  signal?: AbortSignal,
) => {
  return orvalClient<AuditPayload>({
    url: `/api/audit`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiAuditQueryKey = (params?: GetApiAuditParams) => {
  return [`/api/audit`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuditQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAudit>>,
  TError = unknown,
>(
  params?: GetApiAuditParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAudit>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiAuditQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAudit>>> = ({
    signal,
  }) => getApiAudit(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAudit>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuditQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAudit>>
>;
export type GetApiAuditQueryError = unknown;

export function useGetApiAudit<
  TData = Awaited<ReturnType<typeof getApiAudit>>,
  TError = unknown,
>(
  params: undefined | GetApiAuditParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAudit>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAudit>>,
          TError,
          Awaited<ReturnType<typeof getApiAudit>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAudit<
  TData = Awaited<ReturnType<typeof getApiAudit>>,
  TError = unknown,
>(
  params?: GetApiAuditParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAudit>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAudit>>,
          TError,
          Awaited<ReturnType<typeof getApiAudit>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAudit<
  TData = Awaited<ReturnType<typeof getApiAudit>>,
  TError = unknown,
>(
  params?: GetApiAuditParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAudit>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List audit entries
 */

export function useGetApiAudit<
  TData = Awaited<ReturnType<typeof getApiAudit>>,
  TError = unknown,
>(
  params?: GetApiAuditParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAudit>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAuditQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
