/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  Category,
  PatchApiCategoriesIdBody,
  PatchApiCategoriesIdLinesLineIdBody,
  PostApiCategoriesBody,
  PostApiCategoriesIdLinesBody,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary Create category
 */
export const postApiCategories = (
  postApiCategoriesBody: PostApiCategoriesBody,
  signal?: AbortSignal,
) => {
  return orvalClient<Category>({
    url: `/api/categories`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiCategoriesBody,
    signal,
  });
};

export const getPostApiCategoriesQueryKey = (
  postApiCategoriesBody?: PostApiCategoriesBody,
) => {
  return ["POST", `/api/categories`, postApiCategoriesBody] as const;
};

export const getPostApiCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiCategories>>,
  TError = ApiErrorPayload,
>(
  postApiCategoriesBody: PostApiCategoriesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiCategories>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPostApiCategoriesQueryKey(postApiCategoriesBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiCategories>>
  > = ({ signal }) => postApiCategories(postApiCategoriesBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiCategories>>
>;
export type PostApiCategoriesQueryError = ApiErrorPayload;

export function usePostApiCategories<
  TData = Awaited<ReturnType<typeof postApiCategories>>,
  TError = ApiErrorPayload,
>(
  postApiCategoriesBody: PostApiCategoriesBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiCategories>>,
          TError,
          Awaited<ReturnType<typeof postApiCategories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiCategories<
  TData = Awaited<ReturnType<typeof postApiCategories>>,
  TError = ApiErrorPayload,
>(
  postApiCategoriesBody: PostApiCategoriesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiCategories>>,
          TError,
          Awaited<ReturnType<typeof postApiCategories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiCategories<
  TData = Awaited<ReturnType<typeof postApiCategories>>,
  TError = ApiErrorPayload,
>(
  postApiCategoriesBody: PostApiCategoriesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiCategories>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Create category
 */

export function usePostApiCategories<
  TData = Awaited<ReturnType<typeof postApiCategories>>,
  TError = ApiErrorPayload,
>(
  postApiCategoriesBody: PostApiCategoriesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiCategories>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiCategoriesQueryOptions(
    postApiCategoriesBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get category
 */
export const getApiCategoriesId = (id: string, signal?: AbortSignal) => {
  return orvalClient<Category>({
    url: `/api/categories/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiCategoriesIdQueryKey = (id: string) => {
  return [`/api/categories/${id}`] as const;
};

export const getGetApiCategoriesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCategoriesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiCategoriesIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiCategoriesId>>
  > = ({ signal }) => getApiCategoriesId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCategoriesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiCategoriesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiCategoriesId>>
>;
export type GetApiCategoriesIdQueryError = ApiErrorPayload;

export function useGetApiCategoriesId<
  TData = Awaited<ReturnType<typeof getApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCategoriesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoriesId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoriesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCategoriesId<
  TData = Awaited<ReturnType<typeof getApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCategoriesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoriesId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoriesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCategoriesId<
  TData = Awaited<ReturnType<typeof getApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCategoriesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get category
 */

export function useGetApiCategoriesId<
  TData = Awaited<ReturnType<typeof getApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCategoriesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiCategoriesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update category
 */
export const patchApiCategoriesId = (
  id: string,
  patchApiCategoriesIdBody: PatchApiCategoriesIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<Category>({
    url: `/api/categories/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiCategoriesIdBody,
    signal,
  });
};

export const getPatchApiCategoriesIdQueryKey = (
  id: string,
  patchApiCategoriesIdBody?: PatchApiCategoriesIdBody,
) => {
  return ["PATCH", `/api/categories/${id}`, patchApiCategoriesIdBody] as const;
};

export const getPatchApiCategoriesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiCategoriesIdBody: PatchApiCategoriesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiCategoriesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiCategoriesIdQueryKey(id, patchApiCategoriesIdBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiCategoriesId>>
  > = ({ signal }) =>
    patchApiCategoriesId(id, patchApiCategoriesIdBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiCategoriesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiCategoriesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiCategoriesId>>
>;
export type PatchApiCategoriesIdQueryError = ApiErrorPayload;

export function usePatchApiCategoriesId<
  TData = Awaited<ReturnType<typeof patchApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiCategoriesIdBody: PatchApiCategoriesIdBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiCategoriesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiCategoriesId>>,
          TError,
          Awaited<ReturnType<typeof patchApiCategoriesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiCategoriesId<
  TData = Awaited<ReturnType<typeof patchApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiCategoriesIdBody: PatchApiCategoriesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiCategoriesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiCategoriesId>>,
          TError,
          Awaited<ReturnType<typeof patchApiCategoriesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiCategoriesId<
  TData = Awaited<ReturnType<typeof patchApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiCategoriesIdBody: PatchApiCategoriesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiCategoriesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update category
 */

export function usePatchApiCategoriesId<
  TData = Awaited<ReturnType<typeof patchApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiCategoriesIdBody: PatchApiCategoriesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiCategoriesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiCategoriesIdQueryOptions(
    id,
    patchApiCategoriesIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete category
 */
export const deleteApiCategoriesId = (id: string, signal?: AbortSignal) => {
  return orvalClient<unknown>({
    url: `/api/categories/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiCategoriesIdQueryKey = (id: string) => {
  return ["DELETE", `/api/categories/${id}`] as const;
};

export const getDeleteApiCategoriesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiCategoriesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDeleteApiCategoriesIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiCategoriesId>>
  > = ({ signal }) => deleteApiCategoriesId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiCategoriesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiCategoriesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiCategoriesId>>
>;
export type DeleteApiCategoriesIdQueryError = ApiErrorPayload;

export function useDeleteApiCategoriesId<
  TData = Awaited<ReturnType<typeof deleteApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiCategoriesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiCategoriesId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiCategoriesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiCategoriesId<
  TData = Awaited<ReturnType<typeof deleteApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiCategoriesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiCategoriesId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiCategoriesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiCategoriesId<
  TData = Awaited<ReturnType<typeof deleteApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiCategoriesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Delete category
 */

export function useDeleteApiCategoriesId<
  TData = Awaited<ReturnType<typeof deleteApiCategoriesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiCategoriesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiCategoriesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add line
 */
export const postApiCategoriesIdLines = (
  id: string,
  postApiCategoriesIdLinesBody: PostApiCategoriesIdLinesBody,
  signal?: AbortSignal,
) => {
  return orvalClient<Category>({
    url: `/api/categories/${id}/lines`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiCategoriesIdLinesBody,
    signal,
  });
};

export const getPostApiCategoriesIdLinesQueryKey = (
  id: string,
  postApiCategoriesIdLinesBody?: PostApiCategoriesIdLinesBody,
) => {
  return [
    "POST",
    `/api/categories/${id}/lines`,
    postApiCategoriesIdLinesBody,
  ] as const;
};

export const getPostApiCategoriesIdLinesQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiCategoriesIdLinesBody: PostApiCategoriesIdLinesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPostApiCategoriesIdLinesQueryKey(id, postApiCategoriesIdLinesBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiCategoriesIdLines>>
  > = ({ signal }) =>
    postApiCategoriesIdLines(id, postApiCategoriesIdLinesBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiCategoriesIdLinesQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiCategoriesIdLines>>
>;
export type PostApiCategoriesIdLinesQueryError = ApiErrorPayload;

export function usePostApiCategoriesIdLines<
  TData = Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiCategoriesIdLinesBody: PostApiCategoriesIdLinesBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
          TError,
          Awaited<ReturnType<typeof postApiCategoriesIdLines>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiCategoriesIdLines<
  TData = Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiCategoriesIdLinesBody: PostApiCategoriesIdLinesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
          TError,
          Awaited<ReturnType<typeof postApiCategoriesIdLines>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiCategoriesIdLines<
  TData = Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiCategoriesIdLinesBody: PostApiCategoriesIdLinesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Add line
 */

export function usePostApiCategoriesIdLines<
  TData = Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiCategoriesIdLinesBody: PostApiCategoriesIdLinesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiCategoriesIdLines>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiCategoriesIdLinesQueryOptions(
    id,
    postApiCategoriesIdLinesBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update line
 */
export const patchApiCategoriesIdLinesLineId = (
  id: string,
  lineId: string,
  patchApiCategoriesIdLinesLineIdBody: PatchApiCategoriesIdLinesLineIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<Category>({
    url: `/api/categories/${id}/lines/${lineId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiCategoriesIdLinesLineIdBody,
    signal,
  });
};

export const getPatchApiCategoriesIdLinesLineIdQueryKey = (
  id: string,
  lineId: string,
  patchApiCategoriesIdLinesLineIdBody?: PatchApiCategoriesIdLinesLineIdBody,
) => {
  return [
    "PATCH",
    `/api/categories/${id}/lines/${lineId}`,
    patchApiCategoriesIdLinesLineIdBody,
  ] as const;
};

export const getPatchApiCategoriesIdLinesLineIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  lineId: string,
  patchApiCategoriesIdLinesLineIdBody: PatchApiCategoriesIdLinesLineIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiCategoriesIdLinesLineIdQueryKey(
      id,
      lineId,
      patchApiCategoriesIdLinesLineIdBody,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>
  > = ({ signal }) =>
    patchApiCategoriesIdLinesLineId(
      id,
      lineId,
      patchApiCategoriesIdLinesLineIdBody,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled:
      id !== null &&
      id !== undefined &&
      lineId !== null &&
      lineId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiCategoriesIdLinesLineIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>
>;
export type PatchApiCategoriesIdLinesLineIdQueryError = ApiErrorPayload;

export function usePatchApiCategoriesIdLinesLineId<
  TData = Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  lineId: string,
  patchApiCategoriesIdLinesLineIdBody: PatchApiCategoriesIdLinesLineIdBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
          TError,
          Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiCategoriesIdLinesLineId<
  TData = Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  lineId: string,
  patchApiCategoriesIdLinesLineIdBody: PatchApiCategoriesIdLinesLineIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
          TError,
          Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiCategoriesIdLinesLineId<
  TData = Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  lineId: string,
  patchApiCategoriesIdLinesLineIdBody: PatchApiCategoriesIdLinesLineIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update line
 */

export function usePatchApiCategoriesIdLinesLineId<
  TData = Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  lineId: string,
  patchApiCategoriesIdLinesLineIdBody: PatchApiCategoriesIdLinesLineIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiCategoriesIdLinesLineId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiCategoriesIdLinesLineIdQueryOptions(
    id,
    lineId,
    patchApiCategoriesIdLinesLineIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Remove line
 */
export const deleteApiCategoriesIdLinesLineId = (
  id: string,
  lineId: string,
  signal?: AbortSignal,
) => {
  return orvalClient<unknown>({
    url: `/api/categories/${id}/lines/${lineId}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiCategoriesIdLinesLineIdQueryKey = (
  id: string,
  lineId: string,
) => {
  return ["DELETE", `/api/categories/${id}/lines/${lineId}`] as const;
};

export const getDeleteApiCategoriesIdLinesLineIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  lineId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getDeleteApiCategoriesIdLinesLineIdQueryKey(id, lineId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>
  > = ({ signal }) => deleteApiCategoriesIdLinesLineId(id, lineId, signal);

  return {
    queryKey,
    queryFn,
    enabled:
      id !== null &&
      id !== undefined &&
      lineId !== null &&
      lineId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiCategoriesIdLinesLineIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>
>;
export type DeleteApiCategoriesIdLinesLineIdQueryError = ApiErrorPayload;

export function useDeleteApiCategoriesIdLinesLineId<
  TData = Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  lineId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiCategoriesIdLinesLineId<
  TData = Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  lineId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiCategoriesIdLinesLineId<
  TData = Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  lineId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Remove line
 */

export function useDeleteApiCategoriesIdLinesLineId<
  TData = Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  lineId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiCategoriesIdLinesLineId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiCategoriesIdLinesLineIdQueryOptions(
    id,
    lineId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
