/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPagesSlug200 } from "../../model/getApiPagesSlug200";

import type { GetApiPagesSlugParams } from "../../model/getApiPagesSlugParams";

import { serverOrvalClient } from "../../orval-server";

/**
 * @summary Get page
 */
export const getApiPagesSlug = (
  slug: string,
  params?: GetApiPagesSlugParams,
) => {
  return serverOrvalClient<GetApiPagesSlug200>({
    url: `/api/pages/${slug}`,
    method: "GET",
    params,
  });
};
export type GetApiPagesSlugResult = NonNullable<
  Awaited<ReturnType<typeof getApiPagesSlug>>
>;
