/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  PartnerLocation,
  PatchApiPartnerLocationsIdBody,
  PostApiPartnerLocationsBody,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary Create partner location
 */
export const postApiPartnerLocations = (
  postApiPartnerLocationsBody: PostApiPartnerLocationsBody,
  signal?: AbortSignal,
) => {
  return orvalClient<PartnerLocation>({
    url: `/api/partner-locations`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiPartnerLocationsBody,
    signal,
  });
};

export const getPostApiPartnerLocationsQueryKey = (
  postApiPartnerLocationsBody?: PostApiPartnerLocationsBody,
) => {
  return [
    "POST",
    `/api/partner-locations`,
    postApiPartnerLocationsBody,
  ] as const;
};

export const getPostApiPartnerLocationsQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiPartnerLocations>>,
  TError = unknown,
>(
  postApiPartnerLocationsBody: PostApiPartnerLocationsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiPartnerLocations>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPostApiPartnerLocationsQueryKey(postApiPartnerLocationsBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiPartnerLocations>>
  > = ({ signal }) =>
    postApiPartnerLocations(postApiPartnerLocationsBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiPartnerLocations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiPartnerLocationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiPartnerLocations>>
>;
export type PostApiPartnerLocationsQueryError = unknown;

export function usePostApiPartnerLocations<
  TData = Awaited<ReturnType<typeof postApiPartnerLocations>>,
  TError = unknown,
>(
  postApiPartnerLocationsBody: PostApiPartnerLocationsBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiPartnerLocations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiPartnerLocations>>,
          TError,
          Awaited<ReturnType<typeof postApiPartnerLocations>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiPartnerLocations<
  TData = Awaited<ReturnType<typeof postApiPartnerLocations>>,
  TError = unknown,
>(
  postApiPartnerLocationsBody: PostApiPartnerLocationsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiPartnerLocations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiPartnerLocations>>,
          TError,
          Awaited<ReturnType<typeof postApiPartnerLocations>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiPartnerLocations<
  TData = Awaited<ReturnType<typeof postApiPartnerLocations>>,
  TError = unknown,
>(
  postApiPartnerLocationsBody: PostApiPartnerLocationsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiPartnerLocations>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Create partner location
 */

export function usePostApiPartnerLocations<
  TData = Awaited<ReturnType<typeof postApiPartnerLocations>>,
  TError = unknown,
>(
  postApiPartnerLocationsBody: PostApiPartnerLocationsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiPartnerLocations>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiPartnerLocationsQueryOptions(
    postApiPartnerLocationsBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update partner location
 */
export const patchApiPartnerLocationsId = (
  id: string,
  patchApiPartnerLocationsIdBody: PatchApiPartnerLocationsIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<PartnerLocation>({
    url: `/api/partner-locations/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiPartnerLocationsIdBody,
    signal,
  });
};

export const getPatchApiPartnerLocationsIdQueryKey = (
  id: string,
  patchApiPartnerLocationsIdBody?: PatchApiPartnerLocationsIdBody,
) => {
  return [
    "PATCH",
    `/api/partner-locations/${id}`,
    patchApiPartnerLocationsIdBody,
  ] as const;
};

export const getPatchApiPartnerLocationsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiPartnerLocationsIdBody: PatchApiPartnerLocationsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiPartnerLocationsIdQueryKey(id, patchApiPartnerLocationsIdBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiPartnerLocationsId>>
  > = ({ signal }) =>
    patchApiPartnerLocationsId(id, patchApiPartnerLocationsIdBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiPartnerLocationsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiPartnerLocationsId>>
>;
export type PatchApiPartnerLocationsIdQueryError = ApiErrorPayload;

export function usePatchApiPartnerLocationsId<
  TData = Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiPartnerLocationsIdBody: PatchApiPartnerLocationsIdBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
          TError,
          Awaited<ReturnType<typeof patchApiPartnerLocationsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiPartnerLocationsId<
  TData = Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiPartnerLocationsIdBody: PatchApiPartnerLocationsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
          TError,
          Awaited<ReturnType<typeof patchApiPartnerLocationsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiPartnerLocationsId<
  TData = Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiPartnerLocationsIdBody: PatchApiPartnerLocationsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update partner location
 */

export function usePatchApiPartnerLocationsId<
  TData = Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiPartnerLocationsIdBody: PatchApiPartnerLocationsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiPartnerLocationsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiPartnerLocationsIdQueryOptions(
    id,
    patchApiPartnerLocationsIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete partner location
 */
export const deleteApiPartnerLocationsId = (
  id: string,
  signal?: AbortSignal,
) => {
  return orvalClient<unknown>({
    url: `/api/partner-locations/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiPartnerLocationsIdQueryKey = (id: string) => {
  return ["DELETE", `/api/partner-locations/${id}`] as const;
};

export const getDeleteApiPartnerLocationsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDeleteApiPartnerLocationsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>
  > = ({ signal }) => deleteApiPartnerLocationsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiPartnerLocationsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>
>;
export type DeleteApiPartnerLocationsIdQueryError = ApiErrorPayload;

export function useDeleteApiPartnerLocationsId<
  TData = Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiPartnerLocationsId<
  TData = Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiPartnerLocationsId<
  TData = Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Delete partner location
 */

export function useDeleteApiPartnerLocationsId<
  TData = Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiPartnerLocationsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiPartnerLocationsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
