/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  PageBlock,
  PagePayload,
  PatchApiPagesSlugBlocksBlockIdBody,
  PostApiPagesSlugBlocksBody,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary Get page
 */
export const getApiPagesSlugCms = (slug: string, signal?: AbortSignal) => {
  return orvalClient<PagePayload>({
    url: `/api/pages/${slug}/cms`,
    method: "GET",
    signal,
  });
};

export const getGetApiPagesSlugCmsQueryKey = (slug: string) => {
  return [`/api/pages/${slug}/cms`] as const;
};

export const getGetApiPagesSlugCmsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPagesSlugCms>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPagesSlugCms>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiPagesSlugCmsQueryKey(slug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiPagesSlugCms>>
  > = ({ signal }) => getApiPagesSlugCms(slug, signal);

  return {
    queryKey,
    queryFn,
    enabled: slug !== null && slug !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPagesSlugCms>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPagesSlugCmsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPagesSlugCms>>
>;
export type GetApiPagesSlugCmsQueryError = ApiErrorPayload;

export function useGetApiPagesSlugCms<
  TData = Awaited<ReturnType<typeof getApiPagesSlugCms>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPagesSlugCms>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPagesSlugCms>>,
          TError,
          Awaited<ReturnType<typeof getApiPagesSlugCms>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPagesSlugCms<
  TData = Awaited<ReturnType<typeof getApiPagesSlugCms>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPagesSlugCms>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPagesSlugCms>>,
          TError,
          Awaited<ReturnType<typeof getApiPagesSlugCms>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPagesSlugCms<
  TData = Awaited<ReturnType<typeof getApiPagesSlugCms>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPagesSlugCms>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get page
 */

export function useGetApiPagesSlugCms<
  TData = Awaited<ReturnType<typeof getApiPagesSlugCms>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPagesSlugCms>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPagesSlugCmsQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add block
 */
export const postApiPagesSlugBlocks = (
  slug: string,
  postApiPagesSlugBlocksBody: PostApiPagesSlugBlocksBody,
  signal?: AbortSignal,
) => {
  return orvalClient<PageBlock>({
    url: `/api/pages/${slug}/blocks`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiPagesSlugBlocksBody,
    signal,
  });
};

export const getPostApiPagesSlugBlocksQueryKey = (
  slug: string,
  postApiPagesSlugBlocksBody?: PostApiPagesSlugBlocksBody,
) => {
  return [
    "POST",
    `/api/pages/${slug}/blocks`,
    postApiPagesSlugBlocksBody,
  ] as const;
};

export const getPostApiPagesSlugBlocksQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  postApiPagesSlugBlocksBody: PostApiPagesSlugBlocksBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPostApiPagesSlugBlocksQueryKey(slug, postApiPagesSlugBlocksBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiPagesSlugBlocks>>
  > = ({ signal }) =>
    postApiPagesSlugBlocks(slug, postApiPagesSlugBlocksBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: slug !== null && slug !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiPagesSlugBlocksQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiPagesSlugBlocks>>
>;
export type PostApiPagesSlugBlocksQueryError = ApiErrorPayload;

export function usePostApiPagesSlugBlocks<
  TData = Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  postApiPagesSlugBlocksBody: PostApiPagesSlugBlocksBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
          TError,
          Awaited<ReturnType<typeof postApiPagesSlugBlocks>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiPagesSlugBlocks<
  TData = Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  postApiPagesSlugBlocksBody: PostApiPagesSlugBlocksBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
          TError,
          Awaited<ReturnType<typeof postApiPagesSlugBlocks>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiPagesSlugBlocks<
  TData = Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  postApiPagesSlugBlocksBody: PostApiPagesSlugBlocksBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Add block
 */

export function usePostApiPagesSlugBlocks<
  TData = Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  postApiPagesSlugBlocksBody: PostApiPagesSlugBlocksBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiPagesSlugBlocks>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiPagesSlugBlocksQueryOptions(
    slug,
    postApiPagesSlugBlocksBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update block
 */
export const patchApiPagesSlugBlocksBlockId = (
  slug: string,
  blockId: string,
  patchApiPagesSlugBlocksBlockIdBody: PatchApiPagesSlugBlocksBlockIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<PageBlock>({
    url: `/api/pages/${slug}/blocks/${blockId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiPagesSlugBlocksBlockIdBody,
    signal,
  });
};

export const getPatchApiPagesSlugBlocksBlockIdQueryKey = (
  slug: string,
  blockId: string,
  patchApiPagesSlugBlocksBlockIdBody?: PatchApiPagesSlugBlocksBlockIdBody,
) => {
  return [
    "PATCH",
    `/api/pages/${slug}/blocks/${blockId}`,
    patchApiPagesSlugBlocksBlockIdBody,
  ] as const;
};

export const getPatchApiPagesSlugBlocksBlockIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  blockId: string,
  patchApiPagesSlugBlocksBlockIdBody: PatchApiPagesSlugBlocksBlockIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiPagesSlugBlocksBlockIdQueryKey(
      slug,
      blockId,
      patchApiPagesSlugBlocksBlockIdBody,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>
  > = ({ signal }) =>
    patchApiPagesSlugBlocksBlockId(
      slug,
      blockId,
      patchApiPagesSlugBlocksBlockIdBody,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled:
      slug !== null &&
      slug !== undefined &&
      blockId !== null &&
      blockId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiPagesSlugBlocksBlockIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>
>;
export type PatchApiPagesSlugBlocksBlockIdQueryError = ApiErrorPayload;

export function usePatchApiPagesSlugBlocksBlockId<
  TData = Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  blockId: string,
  patchApiPagesSlugBlocksBlockIdBody: PatchApiPagesSlugBlocksBlockIdBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
          TError,
          Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiPagesSlugBlocksBlockId<
  TData = Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  blockId: string,
  patchApiPagesSlugBlocksBlockIdBody: PatchApiPagesSlugBlocksBlockIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
          TError,
          Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiPagesSlugBlocksBlockId<
  TData = Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  blockId: string,
  patchApiPagesSlugBlocksBlockIdBody: PatchApiPagesSlugBlocksBlockIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update block
 */

export function usePatchApiPagesSlugBlocksBlockId<
  TData = Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  blockId: string,
  patchApiPagesSlugBlocksBlockIdBody: PatchApiPagesSlugBlocksBlockIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiPagesSlugBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiPagesSlugBlocksBlockIdQueryOptions(
    slug,
    blockId,
    patchApiPagesSlugBlocksBlockIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Remove block
 */
export const deleteApiPagesSlugBlocksBlockId = (
  slug: string,
  blockId: string,
  signal?: AbortSignal,
) => {
  return orvalClient<unknown>({
    url: `/api/pages/${slug}/blocks/${blockId}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiPagesSlugBlocksBlockIdQueryKey = (
  slug: string,
  blockId: string,
) => {
  return ["DELETE", `/api/pages/${slug}/blocks/${blockId}`] as const;
};

export const getDeleteApiPagesSlugBlocksBlockIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  blockId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getDeleteApiPagesSlugBlocksBlockIdQueryKey(slug, blockId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>
  > = ({ signal }) => deleteApiPagesSlugBlocksBlockId(slug, blockId, signal);

  return {
    queryKey,
    queryFn,
    enabled:
      slug !== null &&
      slug !== undefined &&
      blockId !== null &&
      blockId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiPagesSlugBlocksBlockIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>
>;
export type DeleteApiPagesSlugBlocksBlockIdQueryError = ApiErrorPayload;

export function useDeleteApiPagesSlugBlocksBlockId<
  TData = Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  blockId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiPagesSlugBlocksBlockId<
  TData = Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  blockId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiPagesSlugBlocksBlockId<
  TData = Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  blockId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Remove block
 */

export function useDeleteApiPagesSlugBlocksBlockId<
  TData = Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  blockId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiPagesSlugBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiPagesSlugBlocksBlockIdQueryOptions(
    slug,
    blockId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
