/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  CompleteUploadInputInput,
  PostApiUploadBody,
  PostApiUploadComplete201,
  UploadPresignResponse,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * Returns a presigned uploadUrl for direct S3 PUT and the permanent file_url. PUT the file binary to uploadUrl (no Authorization header — signature is embedded).
 * @summary Generate upload URL
 */
export const postApiUpload = (
  postApiUploadBody: PostApiUploadBody,
  signal?: AbortSignal,
) => {
  return orvalClient<UploadPresignResponse>({
    url: `/api/upload`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiUploadBody,
    signal,
  });
};

export const getPostApiUploadQueryKey = (
  postApiUploadBody?: PostApiUploadBody,
) => {
  return ["POST", `/api/upload`, postApiUploadBody] as const;
};

export const getPostApiUploadQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiUpload>>,
  TError = ApiErrorPayload,
>(
  postApiUploadBody: PostApiUploadBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiUpload>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPostApiUploadQueryKey(postApiUploadBody);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiUpload>>> = ({
    signal,
  }) => postApiUpload(postApiUploadBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiUpload>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiUploadQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiUpload>>
>;
export type PostApiUploadQueryError = ApiErrorPayload;

export function usePostApiUpload<
  TData = Awaited<ReturnType<typeof postApiUpload>>,
  TError = ApiErrorPayload,
>(
  postApiUploadBody: PostApiUploadBody,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiUpload>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUpload>>,
          TError,
          Awaited<ReturnType<typeof postApiUpload>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiUpload<
  TData = Awaited<ReturnType<typeof postApiUpload>>,
  TError = ApiErrorPayload,
>(
  postApiUploadBody: PostApiUploadBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiUpload>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUpload>>,
          TError,
          Awaited<ReturnType<typeof postApiUpload>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiUpload<
  TData = Awaited<ReturnType<typeof postApiUpload>>,
  TError = ApiErrorPayload,
>(
  postApiUploadBody: PostApiUploadBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiUpload>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Generate upload URL
 */

export function usePostApiUpload<
  TData = Awaited<ReturnType<typeof postApiUpload>>,
  TError = ApiErrorPayload,
>(
  postApiUploadBody: PostApiUploadBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiUpload>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiUploadQueryOptions(postApiUploadBody, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register uploaded file in media library
 */
export const postApiUploadComplete = (
  completeUploadInputInput: CompleteUploadInputInput,
  signal?: AbortSignal,
) => {
  return orvalClient<PostApiUploadComplete201>({
    url: `/api/upload/complete`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: completeUploadInputInput,
    signal,
  });
};

export const getPostApiUploadCompleteQueryKey = (
  completeUploadInputInput?: CompleteUploadInputInput,
) => {
  return ["POST", `/api/upload/complete`, completeUploadInputInput] as const;
};

export const getPostApiUploadCompleteQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiUploadComplete>>,
  TError = ApiErrorPayload,
>(
  completeUploadInputInput: CompleteUploadInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiUploadComplete>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPostApiUploadCompleteQueryKey(completeUploadInputInput);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiUploadComplete>>
  > = ({ signal }) => postApiUploadComplete(completeUploadInputInput, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiUploadComplete>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiUploadCompleteQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiUploadComplete>>
>;
export type PostApiUploadCompleteQueryError = ApiErrorPayload;

export function usePostApiUploadComplete<
  TData = Awaited<ReturnType<typeof postApiUploadComplete>>,
  TError = ApiErrorPayload,
>(
  completeUploadInputInput: CompleteUploadInputInput,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiUploadComplete>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUploadComplete>>,
          TError,
          Awaited<ReturnType<typeof postApiUploadComplete>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiUploadComplete<
  TData = Awaited<ReturnType<typeof postApiUploadComplete>>,
  TError = ApiErrorPayload,
>(
  completeUploadInputInput: CompleteUploadInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiUploadComplete>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUploadComplete>>,
          TError,
          Awaited<ReturnType<typeof postApiUploadComplete>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiUploadComplete<
  TData = Awaited<ReturnType<typeof postApiUploadComplete>>,
  TError = ApiErrorPayload,
>(
  completeUploadInputInput: CompleteUploadInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiUploadComplete>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Register uploaded file in media library
 */

export function usePostApiUploadComplete<
  TData = Awaited<ReturnType<typeof postApiUploadComplete>>,
  TError = ApiErrorPayload,
>(
  completeUploadInputInput: CompleteUploadInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiUploadComplete>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiUploadCompleteQueryOptions(
    completeUploadInputInput,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete asset from S3 and media library (soft delete)
 */
export const deleteApiUploadAssetId = (
  assetId: string,
  signal?: AbortSignal,
) => {
  return orvalClient<unknown>({
    url: `/api/upload/${assetId}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiUploadAssetIdQueryKey = (assetId: string) => {
  return ["DELETE", `/api/upload/${assetId}`] as const;
};

export const getDeleteApiUploadAssetIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
  TError = ApiErrorPayload,
>(
  assetId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDeleteApiUploadAssetIdQueryKey(assetId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiUploadAssetId>>
  > = ({ signal }) => deleteApiUploadAssetId(assetId, signal);

  return {
    queryKey,
    queryFn,
    enabled: assetId !== null && assetId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiUploadAssetIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiUploadAssetId>>
>;
export type DeleteApiUploadAssetIdQueryError = ApiErrorPayload;

export function useDeleteApiUploadAssetId<
  TData = Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
  TError = ApiErrorPayload,
>(
  assetId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiUploadAssetId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiUploadAssetId<
  TData = Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
  TError = ApiErrorPayload,
>(
  assetId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiUploadAssetId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiUploadAssetId<
  TData = Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
  TError = ApiErrorPayload,
>(
  assetId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Delete asset from S3 and media library (soft delete)
 */

export function useDeleteApiUploadAssetId<
  TData = Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
  TError = ApiErrorPayload,
>(
  assetId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiUploadAssetId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiUploadAssetIdQueryOptions(assetId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
