/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  CreateLegalPageInputInput,
  LegalPage,
  UpdateLegalPageInputInput,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List all legal pages
 */
export const getApiLegalPages = (signal?: AbortSignal) => {
  return orvalClient<LegalPage[]>({
    url: `/api/legal-pages`,
    method: "GET",
    signal,
  });
};

export const getGetApiLegalPagesQueryKey = () => {
  return [`/api/legal-pages`] as const;
};

export const getGetApiLegalPagesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiLegalPages>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiLegalPages>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiLegalPagesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiLegalPages>>
  > = ({ signal }) => getApiLegalPages(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiLegalPages>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiLegalPagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiLegalPages>>
>;
export type GetApiLegalPagesQueryError = unknown;

export function useGetApiLegalPages<
  TData = Awaited<ReturnType<typeof getApiLegalPages>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPages>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLegalPages>>,
          TError,
          Awaited<ReturnType<typeof getApiLegalPages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLegalPages<
  TData = Awaited<ReturnType<typeof getApiLegalPages>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPages>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLegalPages>>,
          TError,
          Awaited<ReturnType<typeof getApiLegalPages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLegalPages<
  TData = Awaited<ReturnType<typeof getApiLegalPages>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPages>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all legal pages
 */

export function useGetApiLegalPages<
  TData = Awaited<ReturnType<typeof getApiLegalPages>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPages>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiLegalPagesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a legal page
 */
export const postApiLegalPages = (
  createLegalPageInputInput: CreateLegalPageInputInput,
  signal?: AbortSignal,
) => {
  return orvalClient<LegalPage>({
    url: `/api/legal-pages`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createLegalPageInputInput,
    signal,
  });
};

export const getPostApiLegalPagesQueryKey = (
  createLegalPageInputInput?: CreateLegalPageInputInput,
) => {
  return ["POST", `/api/legal-pages`, createLegalPageInputInput] as const;
};

export const getPostApiLegalPagesQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiLegalPages>>,
  TError = ApiErrorPayload,
>(
  createLegalPageInputInput: CreateLegalPageInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiLegalPages>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPostApiLegalPagesQueryKey(createLegalPageInputInput);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiLegalPages>>
  > = ({ signal }) => postApiLegalPages(createLegalPageInputInput, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiLegalPages>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiLegalPagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiLegalPages>>
>;
export type PostApiLegalPagesQueryError = ApiErrorPayload;

export function usePostApiLegalPages<
  TData = Awaited<ReturnType<typeof postApiLegalPages>>,
  TError = ApiErrorPayload,
>(
  createLegalPageInputInput: CreateLegalPageInputInput,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiLegalPages>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiLegalPages>>,
          TError,
          Awaited<ReturnType<typeof postApiLegalPages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiLegalPages<
  TData = Awaited<ReturnType<typeof postApiLegalPages>>,
  TError = ApiErrorPayload,
>(
  createLegalPageInputInput: CreateLegalPageInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiLegalPages>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiLegalPages>>,
          TError,
          Awaited<ReturnType<typeof postApiLegalPages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiLegalPages<
  TData = Awaited<ReturnType<typeof postApiLegalPages>>,
  TError = ApiErrorPayload,
>(
  createLegalPageInputInput: CreateLegalPageInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiLegalPages>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Create a legal page
 */

export function usePostApiLegalPages<
  TData = Awaited<ReturnType<typeof postApiLegalPages>>,
  TError = ApiErrorPayload,
>(
  createLegalPageInputInput: CreateLegalPageInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiLegalPages>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiLegalPagesQueryOptions(
    createLegalPageInputInput,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get a legal page by id
 */
export const getApiLegalPagesId = (id: string, signal?: AbortSignal) => {
  return orvalClient<LegalPage>({
    url: `/api/legal-pages/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiLegalPagesIdQueryKey = (id: string) => {
  return [`/api/legal-pages/${id}`] as const;
};

export const getGetApiLegalPagesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiLegalPagesIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiLegalPagesId>>
  > = ({ signal }) => getApiLegalPagesId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiLegalPagesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiLegalPagesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiLegalPagesId>>
>;
export type GetApiLegalPagesIdQueryError = ApiErrorPayload;

export function useGetApiLegalPagesId<
  TData = Awaited<ReturnType<typeof getApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLegalPagesId>>,
          TError,
          Awaited<ReturnType<typeof getApiLegalPagesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLegalPagesId<
  TData = Awaited<ReturnType<typeof getApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLegalPagesId>>,
          TError,
          Awaited<ReturnType<typeof getApiLegalPagesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLegalPagesId<
  TData = Awaited<ReturnType<typeof getApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a legal page by id
 */

export function useGetApiLegalPagesId<
  TData = Awaited<ReturnType<typeof getApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiLegalPagesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a legal page
 */
export const patchApiLegalPagesId = (
  id: string,
  updateLegalPageInputInput: UpdateLegalPageInputInput,
  signal?: AbortSignal,
) => {
  return orvalClient<LegalPage>({
    url: `/api/legal-pages/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: updateLegalPageInputInput,
    signal,
  });
};

export const getPatchApiLegalPagesIdQueryKey = (
  id: string,
  updateLegalPageInputInput?: UpdateLegalPageInputInput,
) => {
  return [
    "PATCH",
    `/api/legal-pages/${id}`,
    updateLegalPageInputInput,
  ] as const;
};

export const getPatchApiLegalPagesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  updateLegalPageInputInput: UpdateLegalPageInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiLegalPagesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiLegalPagesIdQueryKey(id, updateLegalPageInputInput);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiLegalPagesId>>
  > = ({ signal }) =>
    patchApiLegalPagesId(id, updateLegalPageInputInput, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiLegalPagesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiLegalPagesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiLegalPagesId>>
>;
export type PatchApiLegalPagesIdQueryError = ApiErrorPayload;

export function usePatchApiLegalPagesId<
  TData = Awaited<ReturnType<typeof patchApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  updateLegalPageInputInput: UpdateLegalPageInputInput,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiLegalPagesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiLegalPagesId>>,
          TError,
          Awaited<ReturnType<typeof patchApiLegalPagesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiLegalPagesId<
  TData = Awaited<ReturnType<typeof patchApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  updateLegalPageInputInput: UpdateLegalPageInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiLegalPagesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiLegalPagesId>>,
          TError,
          Awaited<ReturnType<typeof patchApiLegalPagesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiLegalPagesId<
  TData = Awaited<ReturnType<typeof patchApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  updateLegalPageInputInput: UpdateLegalPageInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiLegalPagesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update a legal page
 */

export function usePatchApiLegalPagesId<
  TData = Awaited<ReturnType<typeof patchApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  updateLegalPageInputInput: UpdateLegalPageInputInput,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiLegalPagesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiLegalPagesIdQueryOptions(
    id,
    updateLegalPageInputInput,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete a legal page
 */
export const deleteApiLegalPagesId = (id: string, signal?: AbortSignal) => {
  return orvalClient<unknown>({
    url: `/api/legal-pages/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiLegalPagesIdQueryKey = (id: string) => {
  return ["DELETE", `/api/legal-pages/${id}`] as const;
};

export const getDeleteApiLegalPagesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDeleteApiLegalPagesIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiLegalPagesId>>
  > = ({ signal }) => deleteApiLegalPagesId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiLegalPagesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiLegalPagesId>>
>;
export type DeleteApiLegalPagesIdQueryError = ApiErrorPayload;

export function useDeleteApiLegalPagesId<
  TData = Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiLegalPagesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiLegalPagesId<
  TData = Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiLegalPagesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiLegalPagesId<
  TData = Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Delete a legal page
 */

export function useDeleteApiLegalPagesId<
  TData = Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiLegalPagesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiLegalPagesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
