/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminFaqItem,
  ApiErrorPayload,
  FaqItem,
  PatchApiFaqsIdBody,
  PatchApiFaqsReorderBody,
  PostApiFaqsBody,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary Create FAQ item
 */
export const postApiFaqs = (
  postApiFaqsBody: PostApiFaqsBody,
  signal?: AbortSignal,
) => {
  return orvalClient<FaqItem>({
    url: `/api/faqs`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiFaqsBody,
    signal,
  });
};

export const getPostApiFaqsQueryKey = (postApiFaqsBody?: PostApiFaqsBody) => {
  return ["POST", `/api/faqs`, postApiFaqsBody] as const;
};

export const getPostApiFaqsQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiFaqs>>,
  TError = unknown,
>(
  postApiFaqsBody: PostApiFaqsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiFaqs>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPostApiFaqsQueryKey(postApiFaqsBody);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiFaqs>>> = ({
    signal,
  }) => postApiFaqs(postApiFaqsBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiFaqs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiFaqsQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiFaqs>>
>;
export type PostApiFaqsQueryError = unknown;

export function usePostApiFaqs<
  TData = Awaited<ReturnType<typeof postApiFaqs>>,
  TError = unknown,
>(
  postApiFaqsBody: PostApiFaqsBody,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiFaqs>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiFaqs>>,
          TError,
          Awaited<ReturnType<typeof postApiFaqs>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiFaqs<
  TData = Awaited<ReturnType<typeof postApiFaqs>>,
  TError = unknown,
>(
  postApiFaqsBody: PostApiFaqsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiFaqs>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiFaqs>>,
          TError,
          Awaited<ReturnType<typeof postApiFaqs>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiFaqs<
  TData = Awaited<ReturnType<typeof postApiFaqs>>,
  TError = unknown,
>(
  postApiFaqsBody: PostApiFaqsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiFaqs>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Create FAQ item
 */

export function usePostApiFaqs<
  TData = Awaited<ReturnType<typeof postApiFaqs>>,
  TError = unknown,
>(
  postApiFaqsBody: PostApiFaqsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiFaqs>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiFaqsQueryOptions(postApiFaqsBody, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List FAQ items with full I18nString (ordered)
 */
export const getApiFaqsAdmin = (signal?: AbortSignal) => {
  return orvalClient<AdminFaqItem[]>({
    url: `/api/faqs/admin`,
    method: "GET",
    signal,
  });
};

export const getGetApiFaqsAdminQueryKey = () => {
  return [`/api/faqs/admin`] as const;
};

export const getGetApiFaqsAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiFaqsAdmin>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiFaqsAdmin>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiFaqsAdminQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFaqsAdmin>>> = ({
    signal,
  }) => getApiFaqsAdmin(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiFaqsAdmin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiFaqsAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiFaqsAdmin>>
>;
export type GetApiFaqsAdminQueryError = unknown;

export function useGetApiFaqsAdmin<
  TData = Awaited<ReturnType<typeof getApiFaqsAdmin>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFaqsAdmin>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFaqsAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiFaqsAdmin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFaqsAdmin<
  TData = Awaited<ReturnType<typeof getApiFaqsAdmin>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFaqsAdmin>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFaqsAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiFaqsAdmin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiFaqsAdmin<
  TData = Awaited<ReturnType<typeof getApiFaqsAdmin>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFaqsAdmin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List FAQ items with full I18nString (ordered)
 */

export function useGetApiFaqsAdmin<
  TData = Awaited<ReturnType<typeof getApiFaqsAdmin>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiFaqsAdmin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiFaqsAdminQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Reorder FAQ items
 */
export const patchApiFaqsReorder = (
  patchApiFaqsReorderBody: PatchApiFaqsReorderBody,
  signal?: AbortSignal,
) => {
  return orvalClient<FaqItem[]>({
    url: `/api/faqs/reorder`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiFaqsReorderBody,
    signal,
  });
};

export const getPatchApiFaqsReorderQueryKey = (
  patchApiFaqsReorderBody?: PatchApiFaqsReorderBody,
) => {
  return ["PATCH", `/api/faqs/reorder`, patchApiFaqsReorderBody] as const;
};

export const getPatchApiFaqsReorderQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiFaqsReorder>>,
  TError = unknown,
>(
  patchApiFaqsReorderBody: PatchApiFaqsReorderBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiFaqsReorder>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiFaqsReorderQueryKey(patchApiFaqsReorderBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiFaqsReorder>>
  > = ({ signal }) => patchApiFaqsReorder(patchApiFaqsReorderBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiFaqsReorder>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiFaqsReorderQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiFaqsReorder>>
>;
export type PatchApiFaqsReorderQueryError = unknown;

export function usePatchApiFaqsReorder<
  TData = Awaited<ReturnType<typeof patchApiFaqsReorder>>,
  TError = unknown,
>(
  patchApiFaqsReorderBody: PatchApiFaqsReorderBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiFaqsReorder>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiFaqsReorder>>,
          TError,
          Awaited<ReturnType<typeof patchApiFaqsReorder>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiFaqsReorder<
  TData = Awaited<ReturnType<typeof patchApiFaqsReorder>>,
  TError = unknown,
>(
  patchApiFaqsReorderBody: PatchApiFaqsReorderBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiFaqsReorder>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiFaqsReorder>>,
          TError,
          Awaited<ReturnType<typeof patchApiFaqsReorder>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiFaqsReorder<
  TData = Awaited<ReturnType<typeof patchApiFaqsReorder>>,
  TError = unknown,
>(
  patchApiFaqsReorderBody: PatchApiFaqsReorderBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiFaqsReorder>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Reorder FAQ items
 */

export function usePatchApiFaqsReorder<
  TData = Awaited<ReturnType<typeof patchApiFaqsReorder>>,
  TError = unknown,
>(
  patchApiFaqsReorderBody: PatchApiFaqsReorderBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiFaqsReorder>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiFaqsReorderQueryOptions(
    patchApiFaqsReorderBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update FAQ item
 */
export const patchApiFaqsId = (
  id: string,
  patchApiFaqsIdBody: PatchApiFaqsIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<FaqItem>({
    url: `/api/faqs/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiFaqsIdBody,
    signal,
  });
};

export const getPatchApiFaqsIdQueryKey = (
  id: string,
  patchApiFaqsIdBody?: PatchApiFaqsIdBody,
) => {
  return ["PATCH", `/api/faqs/${id}`, patchApiFaqsIdBody] as const;
};

export const getPatchApiFaqsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiFaqsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiFaqsIdBody: PatchApiFaqsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patchApiFaqsId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPatchApiFaqsIdQueryKey(id, patchApiFaqsIdBody);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof patchApiFaqsId>>> = ({
    signal,
  }) => patchApiFaqsId(id, patchApiFaqsIdBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiFaqsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiFaqsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiFaqsId>>
>;
export type PatchApiFaqsIdQueryError = ApiErrorPayload;

export function usePatchApiFaqsId<
  TData = Awaited<ReturnType<typeof patchApiFaqsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiFaqsIdBody: PatchApiFaqsIdBody,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patchApiFaqsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiFaqsId>>,
          TError,
          Awaited<ReturnType<typeof patchApiFaqsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiFaqsId<
  TData = Awaited<ReturnType<typeof patchApiFaqsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiFaqsIdBody: PatchApiFaqsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patchApiFaqsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiFaqsId>>,
          TError,
          Awaited<ReturnType<typeof patchApiFaqsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiFaqsId<
  TData = Awaited<ReturnType<typeof patchApiFaqsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiFaqsIdBody: PatchApiFaqsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patchApiFaqsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update FAQ item
 */

export function usePatchApiFaqsId<
  TData = Awaited<ReturnType<typeof patchApiFaqsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiFaqsIdBody: PatchApiFaqsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patchApiFaqsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiFaqsIdQueryOptions(
    id,
    patchApiFaqsIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete FAQ item
 */
export const deleteApiFaqsId = (id: string, signal?: AbortSignal) => {
  return orvalClient<unknown>({
    url: `/api/faqs/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiFaqsIdQueryKey = (id: string) => {
  return ["DELETE", `/api/faqs/${id}`] as const;
};

export const getDeleteApiFaqsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiFaqsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiFaqsId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDeleteApiFaqsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteApiFaqsId>>> = ({
    signal,
  }) => deleteApiFaqsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiFaqsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiFaqsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiFaqsId>>
>;
export type DeleteApiFaqsIdQueryError = ApiErrorPayload;

export function useDeleteApiFaqsId<
  TData = Awaited<ReturnType<typeof deleteApiFaqsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiFaqsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiFaqsId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiFaqsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiFaqsId<
  TData = Awaited<ReturnType<typeof deleteApiFaqsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiFaqsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiFaqsId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiFaqsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiFaqsId<
  TData = Awaited<ReturnType<typeof deleteApiFaqsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiFaqsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Delete FAQ item
 */

export function useDeleteApiFaqsId<
  TData = Awaited<ReturnType<typeof deleteApiFaqsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiFaqsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiFaqsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
