/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AdminDashboardPayload } from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary Get dashboard
 */
export const getApiDashboard = (signal?: AbortSignal) => {
  return orvalClient<AdminDashboardPayload>({
    url: `/api/dashboard`,
    method: "GET",
    signal,
  });
};

export const getGetApiDashboardQueryKey = () => {
  return [`/api/dashboard`] as const;
};

export const getGetApiDashboardQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiDashboard>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiDashboard>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiDashboardQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDashboard>>> = ({
    signal,
  }) => getApiDashboard(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiDashboard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiDashboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiDashboard>>
>;
export type GetApiDashboardQueryError = unknown;

export function useGetApiDashboard<
  TData = Awaited<ReturnType<typeof getApiDashboard>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboard>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboard>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboard>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboard<
  TData = Awaited<ReturnType<typeof getApiDashboard>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboard>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboard>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboard>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboard<
  TData = Awaited<ReturnType<typeof getApiDashboard>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboard>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get dashboard
 */

export function useGetApiDashboard<
  TData = Awaited<ReturnType<typeof getApiDashboard>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboard>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiDashboardQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
