/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { GetApiCategoriesParams, PublicCategory } from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List categories
 */
export const getApiCategories = (
  params?: GetApiCategoriesParams,
  signal?: AbortSignal,
) => {
  return orvalClient<PublicCategory[]>({
    url: `/api/categories`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiCategoriesQueryKey = (
  params?: GetApiCategoriesParams,
) => {
  return [`/api/categories`, ...(params ? [params] : [])] as const;
};

export const getGetApiCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCategories>>,
  TError = unknown,
>(
  params?: GetApiCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCategories>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiCategoriesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiCategories>>
  > = ({ signal }) => getApiCategories(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiCategories>>
>;
export type GetApiCategoriesQueryError = unknown;

export function useGetApiCategories<
  TData = Awaited<ReturnType<typeof getApiCategories>>,
  TError = unknown,
>(
  params: undefined | GetApiCategoriesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategories>>,
          TError,
          Awaited<ReturnType<typeof getApiCategories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCategories<
  TData = Awaited<ReturnType<typeof getApiCategories>>,
  TError = unknown,
>(
  params?: GetApiCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategories>>,
          TError,
          Awaited<ReturnType<typeof getApiCategories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiCategories<
  TData = Awaited<ReturnType<typeof getApiCategories>>,
  TError = unknown,
>(
  params?: GetApiCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCategories>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List categories
 */

export function useGetApiCategories<
  TData = Awaited<ReturnType<typeof getApiCategories>>,
  TError = unknown,
>(
  params?: GetApiCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCategories>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiCategoriesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
