/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  CmsProductDetailPayload,
  CmsProductsPayload,
  GetApiProductsAdminParams,
  GetApiProductsParams,
  GetApiProductsSlugParams,
  PatchApiProductsId200,
  PatchApiProductsIdBlocksBlockIdBody,
  PatchApiProductsIdBody,
  PatchApiProductsIdFilesFileIdBody,
  PatchApiProductsIdImagesImageIdBody,
  PostApiProducts201,
  PostApiProductsBody,
  PostApiProductsIdBlocksBody,
  PostApiProductsIdFilesBody,
  PostApiProductsIdImages201,
  PostApiProductsIdImagesBody,
  ProductBlock,
  ProductCatalogResponse,
  ProductDetailPayload,
  ProductFile,
  ProductImage,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List products (public catalog)
 */
export const getApiProducts = (
  params?: GetApiProductsParams,
  signal?: AbortSignal,
) => {
  return orvalClient<ProductCatalogResponse>({
    url: `/api/products/`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiProductsQueryKey = (params?: GetApiProductsParams) => {
  return [`/api/products/`, ...(params ? [params] : [])] as const;
};

export const getGetApiProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProducts>>,
  TError = unknown,
>(
  params?: GetApiProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiProductsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProducts>>> = ({
    signal,
  }) => getApiProducts(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiProducts>>
>;
export type GetApiProductsQueryError = unknown;

export function useGetApiProducts<
  TData = Awaited<ReturnType<typeof getApiProducts>>,
  TError = unknown,
>(
  params: undefined | GetApiProductsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProducts>>,
          TError,
          Awaited<ReturnType<typeof getApiProducts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProducts<
  TData = Awaited<ReturnType<typeof getApiProducts>>,
  TError = unknown,
>(
  params?: GetApiProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProducts>>,
          TError,
          Awaited<ReturnType<typeof getApiProducts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProducts<
  TData = Awaited<ReturnType<typeof getApiProducts>>,
  TError = unknown,
>(
  params?: GetApiProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List products (public catalog)
 */

export function useGetApiProducts<
  TData = Awaited<ReturnType<typeof getApiProducts>>,
  TError = unknown,
>(
  params?: GetApiProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiProductsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create product
 */
export const postApiProducts = (
  postApiProductsBody: PostApiProductsBody,
  signal?: AbortSignal,
) => {
  return orvalClient<PostApiProducts201>({
    url: `/api/products/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiProductsBody,
    signal,
  });
};

export const getPostApiProductsQueryKey = (
  postApiProductsBody?: PostApiProductsBody,
) => {
  return ["POST", `/api/products/`, postApiProductsBody] as const;
};

export const getPostApiProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiProducts>>,
  TError = ApiErrorPayload,
>(
  postApiProductsBody: PostApiProductsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProducts>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPostApiProductsQueryKey(postApiProductsBody);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiProducts>>> = ({
    signal,
  }) => postApiProducts(postApiProductsBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiProducts>>
>;
export type PostApiProductsQueryError = ApiErrorPayload;

export function usePostApiProducts<
  TData = Awaited<ReturnType<typeof postApiProducts>>,
  TError = ApiErrorPayload,
>(
  postApiProductsBody: PostApiProductsBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiProducts>>,
          TError,
          Awaited<ReturnType<typeof postApiProducts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiProducts<
  TData = Awaited<ReturnType<typeof postApiProducts>>,
  TError = ApiErrorPayload,
>(
  postApiProductsBody: PostApiProductsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiProducts>>,
          TError,
          Awaited<ReturnType<typeof postApiProducts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiProducts<
  TData = Awaited<ReturnType<typeof postApiProducts>>,
  TError = ApiErrorPayload,
>(
  postApiProductsBody: PostApiProductsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProducts>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Create product
 */

export function usePostApiProducts<
  TData = Awaited<ReturnType<typeof postApiProducts>>,
  TError = ApiErrorPayload,
>(
  postApiProductsBody: PostApiProductsBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProducts>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiProductsQueryOptions(
    postApiProductsBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get product detail by slug
 */
export const getApiProductsSlug = (
  slug: string,
  params?: GetApiProductsSlugParams,
  signal?: AbortSignal,
) => {
  return orvalClient<ProductDetailPayload>({
    url: `/api/products/${slug}`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiProductsSlugQueryKey = (
  slug: string,
  params?: GetApiProductsSlugParams,
) => {
  return [`/api/products/${slug}`, ...(params ? [params] : [])] as const;
};

export const getGetApiProductsSlugQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProductsSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiProductsSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsSlug>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiProductsSlugQueryKey(slug, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiProductsSlug>>
  > = ({ signal }) => getApiProductsSlug(slug, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: slug !== null && slug !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProductsSlug>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiProductsSlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiProductsSlug>>
>;
export type GetApiProductsSlugQueryError = ApiErrorPayload;

export function useGetApiProductsSlug<
  TData = Awaited<ReturnType<typeof getApiProductsSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params: undefined | GetApiProductsSlugParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsSlug>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsSlug>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProductsSlug<
  TData = Awaited<ReturnType<typeof getApiProductsSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiProductsSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsSlug>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsSlug>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProductsSlug<
  TData = Awaited<ReturnType<typeof getApiProductsSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiProductsSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsSlug>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get product detail by slug
 */

export function useGetApiProductsSlug<
  TData = Awaited<ReturnType<typeof getApiProductsSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiProductsSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsSlug>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiProductsSlugQueryOptions(slug, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List products (CMS)
 */
export const getApiProductsAdmin = (
  params?: GetApiProductsAdminParams,
  signal?: AbortSignal,
) => {
  return orvalClient<CmsProductsPayload>({
    url: `/api/products/admin`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiProductsAdminQueryKey = (
  params?: GetApiProductsAdminParams,
) => {
  return [`/api/products/admin`, ...(params ? [params] : [])] as const;
};

export const getGetApiProductsAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProductsAdmin>>,
  TError = unknown,
>(
  params?: GetApiProductsAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsAdmin>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiProductsAdminQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiProductsAdmin>>
  > = ({ signal }) => getApiProductsAdmin(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProductsAdmin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiProductsAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiProductsAdmin>>
>;
export type GetApiProductsAdminQueryError = unknown;

export function useGetApiProductsAdmin<
  TData = Awaited<ReturnType<typeof getApiProductsAdmin>>,
  TError = unknown,
>(
  params: undefined | GetApiProductsAdminParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsAdmin>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsAdmin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProductsAdmin<
  TData = Awaited<ReturnType<typeof getApiProductsAdmin>>,
  TError = unknown,
>(
  params?: GetApiProductsAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsAdmin>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsAdmin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProductsAdmin<
  TData = Awaited<ReturnType<typeof getApiProductsAdmin>>,
  TError = unknown,
>(
  params?: GetApiProductsAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsAdmin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List products (CMS)
 */

export function useGetApiProductsAdmin<
  TData = Awaited<ReturnType<typeof getApiProductsAdmin>>,
  TError = unknown,
>(
  params?: GetApiProductsAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsAdmin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiProductsAdminQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get product for CMS editing
 */
export const getApiProductsAdminId = (id: string, signal?: AbortSignal) => {
  return orvalClient<CmsProductDetailPayload>({
    url: `/api/products/admin/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiProductsAdminIdQueryKey = (id: string) => {
  return [`/api/products/admin/${id}`] as const;
};

export const getGetApiProductsAdminIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProductsAdminId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsAdminId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiProductsAdminIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiProductsAdminId>>
  > = ({ signal }) => getApiProductsAdminId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProductsAdminId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiProductsAdminIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiProductsAdminId>>
>;
export type GetApiProductsAdminIdQueryError = ApiErrorPayload;

export function useGetApiProductsAdminId<
  TData = Awaited<ReturnType<typeof getApiProductsAdminId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsAdminId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsAdminId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsAdminId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProductsAdminId<
  TData = Awaited<ReturnType<typeof getApiProductsAdminId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsAdminId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsAdminId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsAdminId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProductsAdminId<
  TData = Awaited<ReturnType<typeof getApiProductsAdminId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsAdminId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get product for CMS editing
 */

export function useGetApiProductsAdminId<
  TData = Awaited<ReturnType<typeof getApiProductsAdminId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsAdminId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiProductsAdminIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update product
 */
export const patchApiProductsId = (
  id: string,
  patchApiProductsIdBody: PatchApiProductsIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<PatchApiProductsId200>({
    url: `/api/products/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiProductsIdBody,
    signal,
  });
};

export const getPatchApiProductsIdQueryKey = (
  id: string,
  patchApiProductsIdBody?: PatchApiProductsIdBody,
) => {
  return ["PATCH", `/api/products/${id}`, patchApiProductsIdBody] as const;
};

export const getPatchApiProductsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiProductsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiProductsIdBody: PatchApiProductsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiProductsIdQueryKey(id, patchApiProductsIdBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiProductsId>>
  > = ({ signal }) => patchApiProductsId(id, patchApiProductsIdBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiProductsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiProductsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiProductsId>>
>;
export type PatchApiProductsIdQueryError = ApiErrorPayload;

export function usePatchApiProductsId<
  TData = Awaited<ReturnType<typeof patchApiProductsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiProductsIdBody: PatchApiProductsIdBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiProductsId>>,
          TError,
          Awaited<ReturnType<typeof patchApiProductsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiProductsId<
  TData = Awaited<ReturnType<typeof patchApiProductsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiProductsIdBody: PatchApiProductsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiProductsId>>,
          TError,
          Awaited<ReturnType<typeof patchApiProductsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiProductsId<
  TData = Awaited<ReturnType<typeof patchApiProductsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiProductsIdBody: PatchApiProductsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update product
 */

export function usePatchApiProductsId<
  TData = Awaited<ReturnType<typeof patchApiProductsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiProductsIdBody: PatchApiProductsIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiProductsIdQueryOptions(
    id,
    patchApiProductsIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete product (soft)
 */
export const deleteApiProductsId = (id: string, signal?: AbortSignal) => {
  return orvalClient<unknown>({
    url: `/api/products/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiProductsIdQueryKey = (id: string) => {
  return ["DELETE", `/api/products/${id}`] as const;
};

export const getDeleteApiProductsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiProductsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDeleteApiProductsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiProductsId>>
  > = ({ signal }) => deleteApiProductsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiProductsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiProductsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiProductsId>>
>;
export type DeleteApiProductsIdQueryError = ApiErrorPayload;

export function useDeleteApiProductsId<
  TData = Awaited<ReturnType<typeof deleteApiProductsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiProductsId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiProductsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiProductsId<
  TData = Awaited<ReturnType<typeof deleteApiProductsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiProductsId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiProductsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiProductsId<
  TData = Awaited<ReturnType<typeof deleteApiProductsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Delete product (soft)
 */

export function useDeleteApiProductsId<
  TData = Awaited<ReturnType<typeof deleteApiProductsId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiProductsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add image to product
 */
export const postApiProductsIdImages = (
  id: string,
  postApiProductsIdImagesBody: PostApiProductsIdImagesBody,
  signal?: AbortSignal,
) => {
  return orvalClient<PostApiProductsIdImages201>({
    url: `/api/products/${id}/images`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiProductsIdImagesBody,
    signal,
  });
};

export const getPostApiProductsIdImagesQueryKey = (
  id: string,
  postApiProductsIdImagesBody?: PostApiProductsIdImagesBody,
) => {
  return [
    "POST",
    `/api/products/${id}/images`,
    postApiProductsIdImagesBody,
  ] as const;
};

export const getPostApiProductsIdImagesQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiProductsIdImages>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdImagesBody: PostApiProductsIdImagesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdImages>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPostApiProductsIdImagesQueryKey(id, postApiProductsIdImagesBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiProductsIdImages>>
  > = ({ signal }) =>
    postApiProductsIdImages(id, postApiProductsIdImagesBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiProductsIdImages>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiProductsIdImagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiProductsIdImages>>
>;
export type PostApiProductsIdImagesQueryError = ApiErrorPayload;

export function usePostApiProductsIdImages<
  TData = Awaited<ReturnType<typeof postApiProductsIdImages>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdImagesBody: PostApiProductsIdImagesBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdImages>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiProductsIdImages>>,
          TError,
          Awaited<ReturnType<typeof postApiProductsIdImages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiProductsIdImages<
  TData = Awaited<ReturnType<typeof postApiProductsIdImages>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdImagesBody: PostApiProductsIdImagesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdImages>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiProductsIdImages>>,
          TError,
          Awaited<ReturnType<typeof postApiProductsIdImages>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiProductsIdImages<
  TData = Awaited<ReturnType<typeof postApiProductsIdImages>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdImagesBody: PostApiProductsIdImagesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdImages>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Add image to product
 */

export function usePostApiProductsIdImages<
  TData = Awaited<ReturnType<typeof postApiProductsIdImages>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdImagesBody: PostApiProductsIdImagesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdImages>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiProductsIdImagesQueryOptions(
    id,
    postApiProductsIdImagesBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update image order
 */
export const patchApiProductsIdImagesImageId = (
  id: string,
  imageId: string,
  patchApiProductsIdImagesImageIdBody: PatchApiProductsIdImagesImageIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<ProductImage>({
    url: `/api/products/${id}/images/${imageId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiProductsIdImagesImageIdBody,
    signal,
  });
};

export const getPatchApiProductsIdImagesImageIdQueryKey = (
  id: string,
  imageId: string,
  patchApiProductsIdImagesImageIdBody?: PatchApiProductsIdImagesImageIdBody,
) => {
  return [
    "PATCH",
    `/api/products/${id}/images/${imageId}`,
    patchApiProductsIdImagesImageIdBody,
  ] as const;
};

export const getPatchApiProductsIdImagesImageIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  imageId: string,
  patchApiProductsIdImagesImageIdBody: PatchApiProductsIdImagesImageIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiProductsIdImagesImageIdQueryKey(
      id,
      imageId,
      patchApiProductsIdImagesImageIdBody,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>
  > = ({ signal }) =>
    patchApiProductsIdImagesImageId(
      id,
      imageId,
      patchApiProductsIdImagesImageIdBody,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled:
      id !== null &&
      id !== undefined &&
      imageId !== null &&
      imageId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiProductsIdImagesImageIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>
>;
export type PatchApiProductsIdImagesImageIdQueryError = ApiErrorPayload;

export function usePatchApiProductsIdImagesImageId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  imageId: string,
  patchApiProductsIdImagesImageIdBody: PatchApiProductsIdImagesImageIdBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
          TError,
          Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiProductsIdImagesImageId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  imageId: string,
  patchApiProductsIdImagesImageIdBody: PatchApiProductsIdImagesImageIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
          TError,
          Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiProductsIdImagesImageId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  imageId: string,
  patchApiProductsIdImagesImageIdBody: PatchApiProductsIdImagesImageIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update image order
 */

export function usePatchApiProductsIdImagesImageId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  imageId: string,
  patchApiProductsIdImagesImageIdBody: PatchApiProductsIdImagesImageIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdImagesImageId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiProductsIdImagesImageIdQueryOptions(
    id,
    imageId,
    patchApiProductsIdImagesImageIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Remove image from product
 */
export const deleteApiProductsIdImagesImageId = (
  id: string,
  imageId: string,
  signal?: AbortSignal,
) => {
  return orvalClient<unknown>({
    url: `/api/products/${id}/images/${imageId}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiProductsIdImagesImageIdQueryKey = (
  id: string,
  imageId: string,
) => {
  return ["DELETE", `/api/products/${id}/images/${imageId}`] as const;
};

export const getDeleteApiProductsIdImagesImageIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  imageId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getDeleteApiProductsIdImagesImageIdQueryKey(id, imageId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>
  > = ({ signal }) => deleteApiProductsIdImagesImageId(id, imageId, signal);

  return {
    queryKey,
    queryFn,
    enabled:
      id !== null &&
      id !== undefined &&
      imageId !== null &&
      imageId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiProductsIdImagesImageIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>
>;
export type DeleteApiProductsIdImagesImageIdQueryError = ApiErrorPayload;

export function useDeleteApiProductsIdImagesImageId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  imageId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiProductsIdImagesImageId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  imageId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiProductsIdImagesImageId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  imageId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Remove image from product
 */

export function useDeleteApiProductsIdImagesImageId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  imageId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdImagesImageId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiProductsIdImagesImageIdQueryOptions(
    id,
    imageId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List product page blocks
 */
export const getApiProductsIdBlocks = (id: string, signal?: AbortSignal) => {
  return orvalClient<ProductBlock[]>({
    url: `/api/products/${id}/blocks`,
    method: "GET",
    signal,
  });
};

export const getGetApiProductsIdBlocksQueryKey = (id: string) => {
  return [`/api/products/${id}/blocks`] as const;
};

export const getGetApiProductsIdBlocksQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiProductsIdBlocksQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiProductsIdBlocks>>
  > = ({ signal }) => getApiProductsIdBlocks(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiProductsIdBlocksQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiProductsIdBlocks>>
>;
export type GetApiProductsIdBlocksQueryError = ApiErrorPayload;

export function useGetApiProductsIdBlocks<
  TData = Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsIdBlocks>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProductsIdBlocks<
  TData = Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsIdBlocks>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProductsIdBlocks<
  TData = Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List product page blocks
 */

export function useGetApiProductsIdBlocks<
  TData = Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsIdBlocks>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiProductsIdBlocksQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add block to product page
 */
export const postApiProductsIdBlocks = (
  id: string,
  postApiProductsIdBlocksBody: PostApiProductsIdBlocksBody,
  signal?: AbortSignal,
) => {
  return orvalClient<ProductBlock>({
    url: `/api/products/${id}/blocks`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiProductsIdBlocksBody,
    signal,
  });
};

export const getPostApiProductsIdBlocksQueryKey = (
  id: string,
  postApiProductsIdBlocksBody?: PostApiProductsIdBlocksBody,
) => {
  return [
    "POST",
    `/api/products/${id}/blocks`,
    postApiProductsIdBlocksBody,
  ] as const;
};

export const getPostApiProductsIdBlocksQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdBlocksBody: PostApiProductsIdBlocksBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPostApiProductsIdBlocksQueryKey(id, postApiProductsIdBlocksBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiProductsIdBlocks>>
  > = ({ signal }) =>
    postApiProductsIdBlocks(id, postApiProductsIdBlocksBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiProductsIdBlocksQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiProductsIdBlocks>>
>;
export type PostApiProductsIdBlocksQueryError = ApiErrorPayload;

export function usePostApiProductsIdBlocks<
  TData = Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdBlocksBody: PostApiProductsIdBlocksBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
          TError,
          Awaited<ReturnType<typeof postApiProductsIdBlocks>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiProductsIdBlocks<
  TData = Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdBlocksBody: PostApiProductsIdBlocksBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
          TError,
          Awaited<ReturnType<typeof postApiProductsIdBlocks>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiProductsIdBlocks<
  TData = Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdBlocksBody: PostApiProductsIdBlocksBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Add block to product page
 */

export function usePostApiProductsIdBlocks<
  TData = Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdBlocksBody: PostApiProductsIdBlocksBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdBlocks>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiProductsIdBlocksQueryOptions(
    id,
    postApiProductsIdBlocksBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update product page block
 */
export const patchApiProductsIdBlocksBlockId = (
  id: string,
  blockId: string,
  patchApiProductsIdBlocksBlockIdBody: PatchApiProductsIdBlocksBlockIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<ProductBlock>({
    url: `/api/products/${id}/blocks/${blockId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiProductsIdBlocksBlockIdBody,
    signal,
  });
};

export const getPatchApiProductsIdBlocksBlockIdQueryKey = (
  id: string,
  blockId: string,
  patchApiProductsIdBlocksBlockIdBody?: PatchApiProductsIdBlocksBlockIdBody,
) => {
  return [
    "PATCH",
    `/api/products/${id}/blocks/${blockId}`,
    patchApiProductsIdBlocksBlockIdBody,
  ] as const;
};

export const getPatchApiProductsIdBlocksBlockIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  blockId: string,
  patchApiProductsIdBlocksBlockIdBody: PatchApiProductsIdBlocksBlockIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiProductsIdBlocksBlockIdQueryKey(
      id,
      blockId,
      patchApiProductsIdBlocksBlockIdBody,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>
  > = ({ signal }) =>
    patchApiProductsIdBlocksBlockId(
      id,
      blockId,
      patchApiProductsIdBlocksBlockIdBody,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled:
      id !== null &&
      id !== undefined &&
      blockId !== null &&
      blockId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiProductsIdBlocksBlockIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>
>;
export type PatchApiProductsIdBlocksBlockIdQueryError = ApiErrorPayload;

export function usePatchApiProductsIdBlocksBlockId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  blockId: string,
  patchApiProductsIdBlocksBlockIdBody: PatchApiProductsIdBlocksBlockIdBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
          TError,
          Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiProductsIdBlocksBlockId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  blockId: string,
  patchApiProductsIdBlocksBlockIdBody: PatchApiProductsIdBlocksBlockIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
          TError,
          Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiProductsIdBlocksBlockId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  blockId: string,
  patchApiProductsIdBlocksBlockIdBody: PatchApiProductsIdBlocksBlockIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update product page block
 */

export function usePatchApiProductsIdBlocksBlockId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  blockId: string,
  patchApiProductsIdBlocksBlockIdBody: PatchApiProductsIdBlocksBlockIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiProductsIdBlocksBlockIdQueryOptions(
    id,
    blockId,
    patchApiProductsIdBlocksBlockIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Remove block from product page
 */
export const deleteApiProductsIdBlocksBlockId = (
  id: string,
  blockId: string,
  signal?: AbortSignal,
) => {
  return orvalClient<unknown>({
    url: `/api/products/${id}/blocks/${blockId}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiProductsIdBlocksBlockIdQueryKey = (
  id: string,
  blockId: string,
) => {
  return ["DELETE", `/api/products/${id}/blocks/${blockId}`] as const;
};

export const getDeleteApiProductsIdBlocksBlockIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  blockId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getDeleteApiProductsIdBlocksBlockIdQueryKey(id, blockId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>
  > = ({ signal }) => deleteApiProductsIdBlocksBlockId(id, blockId, signal);

  return {
    queryKey,
    queryFn,
    enabled:
      id !== null &&
      id !== undefined &&
      blockId !== null &&
      blockId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiProductsIdBlocksBlockIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>
>;
export type DeleteApiProductsIdBlocksBlockIdQueryError = ApiErrorPayload;

export function useDeleteApiProductsIdBlocksBlockId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  blockId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiProductsIdBlocksBlockId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  blockId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiProductsIdBlocksBlockId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  blockId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Remove block from product page
 */

export function useDeleteApiProductsIdBlocksBlockId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  blockId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdBlocksBlockId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiProductsIdBlocksBlockIdQueryOptions(
    id,
    blockId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List product downloadable files
 */
export const getApiProductsIdFiles = (id: string, signal?: AbortSignal) => {
  return orvalClient<ProductFile[]>({
    url: `/api/products/${id}/files`,
    method: "GET",
    signal,
  });
};

export const getGetApiProductsIdFilesQueryKey = (id: string) => {
  return [`/api/products/${id}/files`] as const;
};

export const getGetApiProductsIdFilesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProductsIdFiles>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsIdFiles>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiProductsIdFilesQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiProductsIdFiles>>
  > = ({ signal }) => getApiProductsIdFiles(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProductsIdFiles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiProductsIdFilesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiProductsIdFiles>>
>;
export type GetApiProductsIdFilesQueryError = ApiErrorPayload;

export function useGetApiProductsIdFiles<
  TData = Awaited<ReturnType<typeof getApiProductsIdFiles>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsIdFiles>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsIdFiles>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsIdFiles>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProductsIdFiles<
  TData = Awaited<ReturnType<typeof getApiProductsIdFiles>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsIdFiles>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsIdFiles>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsIdFiles>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProductsIdFiles<
  TData = Awaited<ReturnType<typeof getApiProductsIdFiles>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsIdFiles>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List product downloadable files
 */

export function useGetApiProductsIdFiles<
  TData = Awaited<ReturnType<typeof getApiProductsIdFiles>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProductsIdFiles>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiProductsIdFilesQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add downloadable file to product
 */
export const postApiProductsIdFiles = (
  id: string,
  postApiProductsIdFilesBody: PostApiProductsIdFilesBody,
  signal?: AbortSignal,
) => {
  return orvalClient<ProductFile>({
    url: `/api/products/${id}/files`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiProductsIdFilesBody,
    signal,
  });
};

export const getPostApiProductsIdFilesQueryKey = (
  id: string,
  postApiProductsIdFilesBody?: PostApiProductsIdFilesBody,
) => {
  return [
    "POST",
    `/api/products/${id}/files`,
    postApiProductsIdFilesBody,
  ] as const;
};

export const getPostApiProductsIdFilesQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiProductsIdFiles>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdFilesBody: PostApiProductsIdFilesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdFiles>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPostApiProductsIdFilesQueryKey(id, postApiProductsIdFilesBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiProductsIdFiles>>
  > = ({ signal }) =>
    postApiProductsIdFiles(id, postApiProductsIdFilesBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiProductsIdFiles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiProductsIdFilesQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiProductsIdFiles>>
>;
export type PostApiProductsIdFilesQueryError = ApiErrorPayload;

export function usePostApiProductsIdFiles<
  TData = Awaited<ReturnType<typeof postApiProductsIdFiles>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdFilesBody: PostApiProductsIdFilesBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdFiles>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiProductsIdFiles>>,
          TError,
          Awaited<ReturnType<typeof postApiProductsIdFiles>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiProductsIdFiles<
  TData = Awaited<ReturnType<typeof postApiProductsIdFiles>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdFilesBody: PostApiProductsIdFilesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdFiles>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiProductsIdFiles>>,
          TError,
          Awaited<ReturnType<typeof postApiProductsIdFiles>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiProductsIdFiles<
  TData = Awaited<ReturnType<typeof postApiProductsIdFiles>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdFilesBody: PostApiProductsIdFilesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdFiles>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Add downloadable file to product
 */

export function usePostApiProductsIdFiles<
  TData = Awaited<ReturnType<typeof postApiProductsIdFiles>>,
  TError = ApiErrorPayload,
>(
  id: string,
  postApiProductsIdFilesBody: PostApiProductsIdFilesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiProductsIdFiles>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiProductsIdFilesQueryOptions(
    id,
    postApiProductsIdFilesBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update product file metadata
 */
export const patchApiProductsIdFilesFileId = (
  id: string,
  fileId: string,
  patchApiProductsIdFilesFileIdBody: PatchApiProductsIdFilesFileIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<ProductFile>({
    url: `/api/products/${id}/files/${fileId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiProductsIdFilesFileIdBody,
    signal,
  });
};

export const getPatchApiProductsIdFilesFileIdQueryKey = (
  id: string,
  fileId: string,
  patchApiProductsIdFilesFileIdBody?: PatchApiProductsIdFilesFileIdBody,
) => {
  return [
    "PATCH",
    `/api/products/${id}/files/${fileId}`,
    patchApiProductsIdFilesFileIdBody,
  ] as const;
};

export const getPatchApiProductsIdFilesFileIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  fileId: string,
  patchApiProductsIdFilesFileIdBody: PatchApiProductsIdFilesFileIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiProductsIdFilesFileIdQueryKey(
      id,
      fileId,
      patchApiProductsIdFilesFileIdBody,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>
  > = ({ signal }) =>
    patchApiProductsIdFilesFileId(
      id,
      fileId,
      patchApiProductsIdFilesFileIdBody,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled:
      id !== null &&
      id !== undefined &&
      fileId !== null &&
      fileId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiProductsIdFilesFileIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>
>;
export type PatchApiProductsIdFilesFileIdQueryError = ApiErrorPayload;

export function usePatchApiProductsIdFilesFileId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  fileId: string,
  patchApiProductsIdFilesFileIdBody: PatchApiProductsIdFilesFileIdBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
          TError,
          Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiProductsIdFilesFileId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  fileId: string,
  patchApiProductsIdFilesFileIdBody: PatchApiProductsIdFilesFileIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
          TError,
          Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiProductsIdFilesFileId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  fileId: string,
  patchApiProductsIdFilesFileIdBody: PatchApiProductsIdFilesFileIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update product file metadata
 */

export function usePatchApiProductsIdFilesFileId<
  TData = Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  fileId: string,
  patchApiProductsIdFilesFileIdBody: PatchApiProductsIdFilesFileIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiProductsIdFilesFileId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiProductsIdFilesFileIdQueryOptions(
    id,
    fileId,
    patchApiProductsIdFilesFileIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Remove file from product
 */
export const deleteApiProductsIdFilesFileId = (
  id: string,
  fileId: string,
  signal?: AbortSignal,
) => {
  return orvalClient<unknown>({
    url: `/api/products/${id}/files/${fileId}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiProductsIdFilesFileIdQueryKey = (
  id: string,
  fileId: string,
) => {
  return ["DELETE", `/api/products/${id}/files/${fileId}`] as const;
};

export const getDeleteApiProductsIdFilesFileIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  fileId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getDeleteApiProductsIdFilesFileIdQueryKey(id, fileId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>
  > = ({ signal }) => deleteApiProductsIdFilesFileId(id, fileId, signal);

  return {
    queryKey,
    queryFn,
    enabled:
      id !== null &&
      id !== undefined &&
      fileId !== null &&
      fileId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiProductsIdFilesFileIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>
>;
export type DeleteApiProductsIdFilesFileIdQueryError = ApiErrorPayload;

export function useDeleteApiProductsIdFilesFileId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  fileId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiProductsIdFilesFileId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  fileId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiProductsIdFilesFileId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  fileId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Remove file from product
 */

export function useDeleteApiProductsIdFilesFileId<
  TData = Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  fileId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiProductsIdFilesFileId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiProductsIdFilesFileIdQueryOptions(
    id,
    fileId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
