/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  GetApiLegalPagesPublicParams,
  GetApiLegalPagesPublicSlugParams,
  PublicLegalPage,
  PublicLegalPageListItem,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List published legal pages (footer)
 */
export const getApiLegalPagesPublic = (
  params?: GetApiLegalPagesPublicParams,
  signal?: AbortSignal,
) => {
  return orvalClient<PublicLegalPageListItem[]>({
    url: `/api/legal-pages/public`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiLegalPagesPublicQueryKey = (
  params?: GetApiLegalPagesPublicParams,
) => {
  return [`/api/legal-pages/public`, ...(params ? [params] : [])] as const;
};

export const getGetApiLegalPagesPublicQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
  TError = unknown,
>(
  params?: GetApiLegalPagesPublicParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiLegalPagesPublicQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiLegalPagesPublic>>
  > = ({ signal }) => getApiLegalPagesPublic(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiLegalPagesPublicQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiLegalPagesPublic>>
>;
export type GetApiLegalPagesPublicQueryError = unknown;

export function useGetApiLegalPagesPublic<
  TData = Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
  TError = unknown,
>(
  params: undefined | GetApiLegalPagesPublicParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
          TError,
          Awaited<ReturnType<typeof getApiLegalPagesPublic>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLegalPagesPublic<
  TData = Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
  TError = unknown,
>(
  params?: GetApiLegalPagesPublicParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
          TError,
          Awaited<ReturnType<typeof getApiLegalPagesPublic>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLegalPagesPublic<
  TData = Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
  TError = unknown,
>(
  params?: GetApiLegalPagesPublicParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List published legal pages (footer)
 */

export function useGetApiLegalPagesPublic<
  TData = Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
  TError = unknown,
>(
  params?: GetApiLegalPagesPublicParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesPublic>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiLegalPagesPublicQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get a published legal page by slug
 */
export const getApiLegalPagesPublicSlug = (
  slug: string,
  params?: GetApiLegalPagesPublicSlugParams,
  signal?: AbortSignal,
) => {
  return orvalClient<PublicLegalPage>({
    url: `/api/legal-pages/public/${slug}`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiLegalPagesPublicSlugQueryKey = (
  slug: string,
  params?: GetApiLegalPagesPublicSlugParams,
) => {
  return [
    `/api/legal-pages/public/${slug}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetApiLegalPagesPublicSlugQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiLegalPagesPublicSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiLegalPagesPublicSlugQueryKey(slug, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>
  > = ({ signal }) => getApiLegalPagesPublicSlug(slug, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: slug !== null && slug !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiLegalPagesPublicSlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>
>;
export type GetApiLegalPagesPublicSlugQueryError = ApiErrorPayload;

export function useGetApiLegalPagesPublicSlug<
  TData = Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params: undefined | GetApiLegalPagesPublicSlugParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLegalPagesPublicSlug<
  TData = Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiLegalPagesPublicSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLegalPagesPublicSlug<
  TData = Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiLegalPagesPublicSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a published legal page by slug
 */

export function useGetApiLegalPagesPublicSlug<
  TData = Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
  TError = ApiErrorPayload,
>(
  slug: string,
  params?: GetApiLegalPagesPublicSlugParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiLegalPagesPublicSlugQueryOptions(
    slug,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
