/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDashboardPayloadInputMetricsItem } from "./adminDashboardPayloadInputMetricsItem";
import type { AdminDashboardPayloadInputQuickActionsItem } from "./adminDashboardPayloadInputQuickActionsItem";
import type { AdminDashboardPayloadInputRecentActivitiesItem } from "./adminDashboardPayloadInputRecentActivitiesItem";
import type { AdminDashboardPayloadInputScheduleItemsItem } from "./adminDashboardPayloadInputScheduleItemsItem";

export interface AdminDashboardPayloadInput {
  title: string;
  subtitle: string;
  metrics: AdminDashboardPayloadInputMetricsItem[];
  recentActivities: AdminDashboardPayloadInputRecentActivitiesItem[];
  scheduleItems: AdminDashboardPayloadInputScheduleItemsItem[];
  quickActions: AdminDashboardPayloadInputQuickActionsItem[];
}
