/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { UserRoleInput } from "./userRoleInput";

export interface AdminUserInput {
  id: string;
  name: string;
  email: string;
  role: UserRoleInput;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  last_login?: string;
}
