/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDashboardPayloadMetricsItem } from "./adminDashboardPayloadMetricsItem";
import type { AdminDashboardPayloadQuickActionsItem } from "./adminDashboardPayloadQuickActionsItem";
import type { AdminDashboardPayloadRecentActivitiesItem } from "./adminDashboardPayloadRecentActivitiesItem";
import type { AdminDashboardPayloadScheduleItemsItem } from "./adminDashboardPayloadScheduleItemsItem";

export interface AdminDashboardPayload {
  title: string;
  subtitle: string;
  metrics: AdminDashboardPayloadMetricsItem[];
  recentActivities: AdminDashboardPayloadRecentActivitiesItem[];
  scheduleItems: AdminDashboardPayloadScheduleItemsItem[];
  quickActions: AdminDashboardPayloadQuickActionsItem[];
}
