/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDashboardPayloadInputScheduleItemsItemType } from "./adminDashboardPayloadInputScheduleItemsItemType";

export type AdminDashboardPayloadInputScheduleItemsItem = {
  id: string;
  label: string;
  date: string;
  type: AdminDashboardPayloadInputScheduleItemsItemType;
};
