/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type AdminDashboardPayloadScheduleItemsItemType =
  (typeof AdminDashboardPayloadScheduleItemsItemType)[keyof typeof AdminDashboardPayloadScheduleItemsItemType];

export const AdminDashboardPayloadScheduleItemsItemType = {
  banner: "banner",
  product: "product",
  other: "other",
} as const;
