/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type AdminDashboardPayloadInputRecentActivitiesItem = {
  id: string;
  title: string;
  description: string;
  timestamp: string;
  user_name: string;
  action: string;
};
