/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { AuditEntryInput } from "./auditEntryInput";

export interface AuditPayloadInput {
  items: AuditEntryInput[];
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  total: number;
}
