/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { UploadIntentInput } from "./uploadIntentInput";

export type BannerWithUploadsInputUploads = {
  desktop?: UploadIntentInput;
  mobile?: UploadIntentInput;
};
