/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { DepartmentConfigItemInput } from "./departmentConfigItemInput";
import type { I18nStringInput } from "./i18nStringInput";

export interface CmsConfigInput {
  company_name: string;
  company_email: string;
  company_phone: string;
  company_whatsapp: string;
  company_address: string;
  social_instagram?: string;
  social_facebook?: string;
  social_youtube?: string;
  social_linkedin?: string;
  /** Contact form department routing — each entry maps a slug to an internal email */
  contact_departments?: DepartmentConfigItemInput[];
  /** Logo variant for light backgrounds, by locale */
  logo_dark?: I18nStringInput;
  /** Logo variant for dark backgrounds, by locale */
  logo_white?: I18nStringInput;
  updated_at: string;
  updated_by: string;
}
