/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export interface CmsConfigInput {
  company_name: string;
  company_email: string;
  company_phone: string;
  company_whatsapp: string;
  company_address: string;
  social_instagram?: string;
  social_facebook?: string;
  social_youtube?: string;
  updated_at: string;
  updated_by: string;
}
