/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { CmsProductRowInput } from "./cmsProductRowInput";

export interface CmsProductsPayloadInput {
  title: string;
  subtitle: string;
  items: CmsProductRowInput[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}
