/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { CreateLegalPageInputTitle } from "./createLegalPageInputTitle";
import type { LegalHtmlI18n } from "./legalHtmlI18n";

export interface CreateLegalPageInput {
  /**
   * @minLength 1
   * @maxLength 200
   */
  slug: string;
  title: CreateLegalPageInputTitle;
  content: LegalHtmlI18n;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  order: number;
  published: boolean;
}
