/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export interface DepartmentConfigItemInput {
  /**
   * URL-friendly department identifier
   * @minLength 1
   */
  slug: string;
  /**
   * Display name shown in the contact form
   * @minLength 1
   */
  label: string;
  /**
   * Internal recipient for this department
   * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email: string;
}
