/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProductsStatus } from "./getApiProductsStatus";
import type { LocaleInput } from "./localeInput";

export type GetApiProductsParams = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
  q?: string;
  category?: string;
  status?: (typeof GetApiProductsStatus)[keyof typeof GetApiProductsStatus];
  locale?: LocaleInput;
  is_featured?: boolean;
  is_spotlight?: boolean;
};
