/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPartnerLocationsType } from "./getApiPartnerLocationsType";

export type GetApiPartnerLocationsParams = {
  type?: GetApiPartnerLocationsType;
  state?: string;
  city?: string;
  region?: string;
  specialty?: string;
  /**
   * Center latitude for proximity search
   * @minimum -90
   * @maximum 90
   */
  lat?: number;
  /**
   * Center longitude for proximity search
   * @minimum -180
   * @maximum 180
   */
  lng?: number;
  /**
   * Max distance radius in km. Defaults to 50 when lat/lng are provided
   * @minimum 0
   */
  max_distance_km?: number;
  is_active?: boolean;
};
