/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type GetApiProductsSlug200ProductStatus =
  (typeof GetApiProductsSlug200ProductStatus)[keyof typeof GetApiProductsSlug200ProductStatus];

export const GetApiProductsSlug200ProductStatus = {
  PUBLISHED: "PUBLISHED",
  DRAFT: "DRAFT",
  SCHEDULED: "SCHEDULED",
} as const;
