/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPagesSlug200BlocksItemDataTabsItem } from "./getApiPagesSlug200BlocksItemDataTabsItem";

export type GetApiPagesSlug200BlocksItemData = {
  tabs?: GetApiPagesSlug200BlocksItemDataTabsItem[];
  [key: string]: unknown;
};
