/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { ProductCardItem } from "./productCardItem";
import type { PublicCategory } from "./publicCategory";
import type { PublicProduct } from "./publicProduct";

export type GetApiProductsSlug200 = {
  product: PublicProduct;
  category: PublicCategory;
  relatedProducts: ProductCardItem[];
};
