/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type GetApiPartnerLocationsType =
  (typeof GetApiPartnerLocationsType)[keyof typeof GetApiPartnerLocationsType];

export const GetApiPartnerLocationsType = {
  REPRESENTATIVE: "REPRESENTATIVE",
  SERVICE_CENTER: "SERVICE_CENTER",
} as const;
