/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type GetApiProductsSort =
  (typeof GetApiProductsSort)[keyof typeof GetApiProductsSort];

export const GetApiProductsSort = {
  relevance: "relevance",
  newest: "newest",
} as const;
