/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiLibraryType } from "./getApiLibraryType";

export type GetApiLibraryParams = {
  type?: GetApiLibraryType;
  q?: string;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  offset?: number;
};
