/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPagesSlug200BlocksItem } from "./getApiPagesSlug200BlocksItem";

export type GetApiPagesSlug200 = {
  id: string;
  slug: string;
  title: string;
  blocks: GetApiPagesSlug200BlocksItem[];
  updated_at: string;
};
