/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPagesSlug200BlocksItemData } from "./getApiPagesSlug200BlocksItemData";
import type { GetApiPagesSlug200BlocksItemType } from "./getApiPagesSlug200BlocksItemType";

export type GetApiPagesSlug200BlocksItem = {
  block_id: string;
  section_id: string;
  type: GetApiPagesSlug200BlocksItemType;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order: number;
  data: GetApiPagesSlug200BlocksItemData;
  available_locales: string[];
};
