/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPartnerLocationsType } from "./getApiPartnerLocationsType";

export type GetApiPartnerLocationsParams = {
  type?: GetApiPartnerLocationsType;
  state?: string;
  region?: string;
  specialty?: string;
  is_active?: boolean;
};
