/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPagesSlug200BlocksItemDataTabsItemCategory } from "./getApiPagesSlug200BlocksItemDataTabsItemCategory";
import type { ProductCardItem } from "./productCardItem";

export type GetApiPagesSlug200BlocksItemDataTabsItem = {
  category: GetApiPagesSlug200BlocksItemDataTabsItemCategory;
  products: ProductCardItem[];
};
