/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export interface LegalHtmlI18nInput {
  /**
   * Sanitized HTML body in Portuguese (required)
   * @minLength 1
   */
  pt: string;
  /** Sanitized HTML body in English */
  en?: string;
  /** Sanitized HTML body in Spanish */
  es?: string;
}
