/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { AssetVersion } from "./assetVersion";
import type { I18nString } from "./i18nString";
import type { LibraryAssetType } from "./libraryAssetType";

export interface LibraryAsset {
  id: string;
  filename: string;
  type: LibraryAssetType;
  alt?: I18nString;
  tags: string[];
  current_version_id: string;
  versions: AssetVersion[];
  created_at: string;
  created_by: string;
}
