/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type Locale = (typeof Locale)[keyof typeof Locale];

export const Locale = {
  pt: "pt",
  en: "en",
  es: "es",
} as const;
