/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { I18nStringInput } from "./i18nStringInput";
import type { PageBlockInput } from "./pageBlockInput";

export interface PagePayloadInput {
  id: string;
  slug: string;
  title: I18nStringInput;
  blocks: PageBlockInput[];
  updated_at: string;
}
