/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { PartnerLocationInputType } from "./partnerLocationInputType";

export interface PartnerLocationInput {
  id: string;
  type: PartnerLocationInputType;
  name: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  lat?: number;
  lng?: number;
  phone?: string;
  phone2?: string;
  email?: string;
  website?: string;
  region?: string;
  specialty?: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
