/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type PartnerLocationInputType =
  (typeof PartnerLocationInputType)[keyof typeof PartnerLocationInputType];

export const PartnerLocationInputType = {
  REPRESENTATIVE: "REPRESENTATIVE",
  SERVICE_CENTER: "SERVICE_CENTER",
} as const;
