/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiLibraryIdBodyAlt } from "./patchApiLibraryIdBodyAlt";

export type PatchApiLibraryIdBody = {
  /**
   * @minLength 1
   * @maxLength 255
   */
  filename?: string;
  /** @nullable */
  alt?: PatchApiLibraryIdBodyAlt;
  tags?: string[];
};
