/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiProductsIdBodySlug = {
  /**
   * @minLength 1
   * @maxLength 120
   * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
   */
  pt: string;
  /**
   * @maxLength 120
   * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
   */
  en?: string;
  /**
   * @maxLength 120
   * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
   */
  es?: string;
};
