/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { LocaleInput } from "./localeInput";
import type { PatchApiPagesSlugBlocksBlockIdBodyData } from "./patchApiPagesSlugBlocksBlockIdBodyData";
import type { PatchApiPagesSlugBlocksBlockIdBodyType } from "./patchApiPagesSlugBlocksBlockIdBodyType";

export type PatchApiPagesSlugBlocksBlockIdBody = {
  /** @maxLength 100 */
  section_id?: string;
  type?: PatchApiPagesSlugBlocksBlockIdBodyType;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order?: number;
  data?: PatchApiPagesSlugBlocksBlockIdBodyData;
  available_locales?: LocaleInput[];
};
