/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiAttributesIdBodyType =
  (typeof PatchApiAttributesIdBodyType)[keyof typeof PatchApiAttributesIdBodyType];

export const PatchApiAttributesIdBodyType = {
  TEXT: "TEXT",
  MATRIX: "MATRIX",
} as const;
