/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiAttributesIdBodyName } from "./patchApiAttributesIdBodyName";
import type { PatchApiAttributesIdBodyType } from "./patchApiAttributesIdBodyType";

export type PatchApiAttributesIdBody = {
  name?: PatchApiAttributesIdBodyName;
  type?: PatchApiAttributesIdBodyType;
};
