/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiFaqsBodyA } from "./postApiFaqsBodyA";
import type { PostApiFaqsBodyQ } from "./postApiFaqsBodyQ";

export type PostApiFaqsBody = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order?: number;
  q: PostApiFaqsBodyQ;
  a: PostApiFaqsBodyA;
};
