/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAttributesBodyName } from "./postApiAttributesBodyName";
import type { PostApiAttributesBodyType } from "./postApiAttributesBodyType";

export type PostApiAttributesBody = {
  name: PostApiAttributesBodyName;
  type?: PostApiAttributesBodyType;
};
