/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { LibraryAsset } from "./libraryAsset";
import type { UploadIntent } from "./uploadIntent";

export type PostApiLibraryIdVersions201 = {
  asset: LibraryAsset;
  upload: UploadIntent;
};
