/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiContactBodyDepartment } from "./postApiContactBodyDepartment";

export type PostApiContactBody = {
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @maxLength 30 */
  phone?: string;
  /**
   * @minLength 3
   * @maxLength 200
   */
  subject: string;
  /**
   * @minLength 10
   * @maxLength 5000
   */
  message: string;
  department: PostApiContactBodyDepartment;
};
