/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPartnerLocationsImportWorkbook200SheetsItemRowsItemValues } from "./postApiPartnerLocationsImportWorkbook200SheetsItemRowsItemValues";

export type PostApiPartnerLocationsImportWorkbook200SheetsItemRowsItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  line: number;
  values: PostApiPartnerLocationsImportWorkbook200SheetsItemRowsItemValues;
  original: string[];
};
