/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPartnerLocationsImport200ErrorsItem = {
  sheet?: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  line: number;
  field?: string;
  reason: string;
  orientation?: string;
  original?: string[];
};
