/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type PostApiBannersBodyTitle = {
  /**
   * @minLength 1
   * @maxLength 2000
   */
  pt: string;
  /** @maxLength 2000 */
  en?: string;
  /** @maxLength 2000 */
  es?: string;
} | null;
