/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPartnerLocationsImportWorkbook200ReportSkippedItem = {
  sheet?: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  line: number;
  name: string;
};
