/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPartnerLocationsImportBodyType } from "./postApiPartnerLocationsImportBodyType";

export type PostApiPartnerLocationsImportBody = {
  /**
   * Raw CSV file contents
   * @minLength 1
   * @maxLength 2000000
   */
  csv: string;
  /** Applied to every row in the file */
  type: PostApiPartnerLocationsImportBodyType;
  /** When true, validates and reports without writing anything */
  dry_run?: boolean;
};
