/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPartnerLocationsImportWorkbook200SheetsItemSuggestedType =
  (typeof PostApiPartnerLocationsImportWorkbook200SheetsItemSuggestedType)[keyof typeof PostApiPartnerLocationsImportWorkbook200SheetsItemSuggestedType];

export const PostApiPartnerLocationsImportWorkbook200SheetsItemSuggestedType = {
  REPRESENTATIVE: "REPRESENTATIVE",
  SERVICE_CENTER: "SERVICE_CENTER",
} as const;
