/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type PostApiProductsBodyStatus =
  (typeof PostApiProductsBodyStatus)[keyof typeof PostApiProductsBodyStatus];

export const PostApiProductsBodyStatus = {
  PUBLISHED: "PUBLISHED",
  DRAFT: "DRAFT",
  SCHEDULED: "SCHEDULED",
} as const;
