/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { LocaleInput } from "./localeInput";
import type { PostApiPagesSlugBlocksBodyData } from "./postApiPagesSlugBlocksBodyData";
import type { PostApiPagesSlugBlocksBodyType } from "./postApiPagesSlugBlocksBodyType";

export type PostApiPagesSlugBlocksBody = {
  /**
   * @minLength 1
   * @maxLength 100
   */
  section_id: string;
  type: PostApiPagesSlugBlocksBodyType;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order?: number;
  data?: PostApiPagesSlugBlocksBodyData;
  available_locales?: LocaleInput[];
};
