/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPartnerLocationsImportWorkbook200SheetsItemRowsItem } from "./postApiPartnerLocationsImportWorkbook200SheetsItemRowsItem";
import type { PostApiPartnerLocationsImportWorkbook200SheetsItemStatus } from "./postApiPartnerLocationsImportWorkbook200SheetsItemStatus";
import type { PostApiPartnerLocationsImportWorkbook200SheetsItemSuggestedType } from "./postApiPartnerLocationsImportWorkbook200SheetsItemSuggestedType";

export type PostApiPartnerLocationsImportWorkbook200SheetsItem = {
  name: string;
  status: PostApiPartnerLocationsImportWorkbook200SheetsItemStatus;
  reason?: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  headerRow?: number;
  headers: string[];
  suggestedType?: PostApiPartnerLocationsImportWorkbook200SheetsItemSuggestedType;
  rows: PostApiPartnerLocationsImportWorkbook200SheetsItemRowsItem[];
};
