/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { LocaleInput } from "./localeInput";
import type { PostApiProductsBodyDescription } from "./postApiProductsBodyDescription";
import type { PostApiProductsBodyName } from "./postApiProductsBodyName";
import type { PostApiProductsBodySlug } from "./postApiProductsBodySlug";
import type { PostApiProductsBodyStatus } from "./postApiProductsBodyStatus";
import type { PostApiProductsBodyVariantsItem } from "./postApiProductsBodyVariantsItem";

export type PostApiProductsBody = {
  name: PostApiProductsBodyName;
  slug: PostApiProductsBodySlug;
  description?: PostApiProductsBodyDescription;
  category_id: string;
  /** @nullable */
  line_id?: string | null;
  /** @nullable */
  template_id?: string | null;
  /**
   * @maxLength 2048
   * @nullable
   */
  app_store_url?: string | null;
  /**
   * @maxLength 2048
   * @nullable
   */
  play_store_url?: string | null;
  status?: PostApiProductsBodyStatus;
  is_discontinued?: boolean;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
   */
  launch_date?: string | null;
  is_featured?: boolean;
  is_spotlight?: boolean;
  available_locales?: LocaleInput[];
  highlight_attributes?: string[];
  variants?: PostApiProductsBodyVariantsItem[];
};
