/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { ProductCardItemInputHighlightedSpecsItem } from "./productCardItemInputHighlightedSpecsItem";
import type { ProductCardItemInputStatus } from "./productCardItemInputStatus";

export interface ProductCardItemInput {
  id: string;
  slug: string;
  name: string;
  category: string;
  /** @nullable */
  line: string | null;
  /** @nullable */
  thumbnail_url: string | null;
  href: string;
  status: ProductCardItemInputStatus;
  is_discontinued: boolean;
  highlighted_specs: ProductCardItemInputHighlightedSpecsItem[];
  /** Variant names available for this product, e.g. "1 Ohm" */
  variants: string[];
}
