/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type ProductBlockInputType =
  (typeof ProductBlockInputType)[keyof typeof ProductBlockInputType];

export const ProductBlockInputType = {
  IMAGE: "IMAGE",
  VIDEO: "VIDEO",
  HTML: "HTML",
  MODEL3D: "MODEL3D",
  TEXT: "TEXT",
  GALLERY: "GALLERY",
} as const;
