/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { I18nStringInput } from "./i18nStringInput";
import type { ProductBlockInput } from "./productBlockInput";
import type { ProductFileInput } from "./productFileInput";
import type { ProductImageInput } from "./productImageInput";
import type { ProductInputStatus } from "./productInputStatus";
import type { VariantInput } from "./variantInput";

export interface ProductInput {
  id: string;
  /** @nullable */
  sku?: string | null;
  name: I18nStringInput;
  slug: I18nStringInput;
  description?: I18nStringInput | null;
  status: ProductInputStatus;
  is_discontinued: boolean;
  /** @nullable */
  launch_date?: string | null;
  is_featured: boolean;
  is_spotlight: boolean;
  available_locales: string[];
  category_id: string;
  /** @nullable */
  line_id?: string | null;
  /** @nullable */
  template_id?: string | null;
  highlight_attributes: string[];
  images: ProductImageInput[];
  variants: VariantInput[];
  page_blocks: ProductBlockInput[];
  files: ProductFileInput[];
  created_at: string;
  updated_at: string;
  created_by: string;
}
