/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from "./category";
import type { Product } from "./product";
import type { ProductCardItem } from "./productCardItem";

export interface ProductDetailPayload {
  product: Product;
  category: Category;
  relatedProducts: ProductCardItem[];
}
