/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { I18nString } from "./i18nString";
import type { ProductBlock } from "./productBlock";
import type { ProductFile } from "./productFile";
import type { ProductImage } from "./productImage";
import type { ProductStatus } from "./productStatus";
import type { Variant } from "./variant";

export interface Product {
  id: string;
  /** @nullable */
  sku?: string | null;
  name: I18nString;
  slug: I18nString;
  description?: I18nString | null;
  status: ProductStatus;
  is_discontinued: boolean;
  /** @nullable */
  launch_date?: string | null;
  is_featured: boolean;
  is_spotlight: boolean;
  available_locales: string[];
  category_id: string;
  /** @nullable */
  line_id?: string | null;
  /** @nullable */
  template_id?: string | null;
  /** @nullable */
  app_store_url?: string | null;
  /** @nullable */
  play_store_url?: string | null;
  highlight_attributes: string[];
  images: ProductImage[];
  variants: Variant[];
  page_blocks: ProductBlock[];
  files: ProductFile[];
  created_at: string;
  updated_at: string;
  created_by: string;
}
