/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryInput } from "./categoryInput";
import type { ProductCardItemInput } from "./productCardItemInput";
import type { ProductInput } from "./productInput";

export interface ProductDetailPayloadInput {
  product: ProductInput;
  category: CategoryInput;
  relatedProducts: ProductCardItemInput[];
}
