/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { ProductCardItemInput } from "./productCardItemInput";

export interface ProductCatalogResponseInput {
  items: ProductCardItemInput[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}
