/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ProductInputDescription = {
  /** @maxLength 20000 */
  pt: string;
  /** @maxLength 20000 */
  en?: string;
  /** @maxLength 20000 */
  es?: string;
} | null;
