/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { ProductCardItemHighlightedSpecsItem } from "./productCardItemHighlightedSpecsItem";
import type { ProductCardItemStatus } from "./productCardItemStatus";

export interface ProductCardItem {
  id: string;
  slug: string;
  name: string;
  category: string;
  /** @nullable */
  line: string | null;
  /** @nullable */
  thumbnail_url: string | null;
  href: string;
  status: ProductCardItemStatus;
  is_discontinued: boolean;
  highlighted_specs: ProductCardItemHighlightedSpecsItem[];
}
