/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { ProductBlockInput } from "./productBlockInput";
import type { ProductFileInput } from "./productFileInput";
import type { ProductImageInput } from "./productImageInput";
import type { PublicProductInputStatus } from "./publicProductInputStatus";
import type { PublicVariantInput } from "./publicVariantInput";

export interface PublicProductInput {
  id: string;
  /** @nullable */
  sku?: string | null;
  name: string;
  slug: string;
  /** @nullable */
  description?: string | null;
  status: PublicProductInputStatus;
  is_discontinued: boolean;
  /** @nullable */
  launch_date?: string | null;
  is_featured: boolean;
  is_spotlight: boolean;
  available_locales: string[];
  category_id: string;
  /** @nullable */
  line_id?: string | null;
  /** @nullable */
  template_id?: string | null;
  /** @nullable */
  app_store_url?: string | null;
  /** @nullable */
  play_store_url?: string | null;
  highlight_attributes: string[];
  images: ProductImageInput[];
  variants: PublicVariantInput[];
  page_blocks: ProductBlockInput[];
  files: ProductFileInput[];
  created_at: string;
  updated_at: string;
  created_by: string;
}
