/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { PublicLineInput } from "./publicLineInput";

export interface PublicCategoryInput {
  id: string;
  name: string;
  slug: string;
  icon_library_id?: string;
  lines: PublicLineInput[];
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order: number;
  created_at: string;
  updated_at: string;
}
