/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type PublicVariantAttrInputAttributeType =
  (typeof PublicVariantAttrInputAttributeType)[keyof typeof PublicVariantAttrInputAttributeType];

export const PublicVariantAttrInputAttributeType = {
  TEXT: "TEXT",
  MATRIX: "MATRIX",
} as const;
