/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export interface PublicDepartmentItemInput {
  /** @minLength 1 */
  slug: string;
  /** @minLength 1 */
  label: string;
}
