/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export interface PublicConfig {
  company_email: string;
  company_phone: string;
  company_whatsapp: string;
  company_address: string;
  /** Logo URL for light backgrounds, resolved to the requested locale */
  logo_dark?: string;
  /** Logo URL for dark backgrounds, resolved to the requested locale */
  logo_white?: string;
  social_instagram?: string;
  social_facebook?: string;
  social_youtube?: string;
  social_linkedin?: string;
}
