/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export interface PublicLegalPageListItem {
  slug: string;
  /** Title resolved to the requested locale */
  title: string;
}
