/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export interface PublicLegalPage {
  slug: string;
  /** Title resolved to the requested locale */
  title: string;
  /** HTML body resolved to the requested locale */
  html: string;
}
