/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { I18nStringInput } from "./i18nStringInput";
import type { TemplateAttrInput } from "./templateAttrInput";

export interface TemplateInput {
  id: string;
  category_id: string;
  name: I18nStringInput;
  attributes: TemplateAttrInput[];
  created_at: string;
  updated_at: string;
}
