/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { LegalHtmlI18nInput } from "./legalHtmlI18nInput";
import type { UpdateLegalPageInputInputTitle } from "./updateLegalPageInputInputTitle";

export interface UpdateLegalPageInputInput {
  /**
   * @minLength 1
   * @maxLength 200
   */
  slug?: string;
  title?: UpdateLegalPageInputInputTitle;
  content?: LegalHtmlI18nInput;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  order?: number;
  published?: boolean;
}
