/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { LegalHtmlI18n } from "./legalHtmlI18n";
import type { UpdateLegalPageInputTitle } from "./updateLegalPageInputTitle";

export interface UpdateLegalPageInput {
  /**
   * @minLength 1
   * @maxLength 200
   */
  slug?: string;
  title?: UpdateLegalPageInputTitle;
  content?: LegalHtmlI18n;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  order?: number;
  published?: boolean;
}
