/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { UploadIntentHeaders } from "./uploadIntentHeaders";
import type { UploadIntentMethod } from "./uploadIntentMethod";

export interface UploadIntent {
  uploadUrl: string;
  method: UploadIntentMethod;
  headers: UploadIntentHeaders;
}
