/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type UploadIntentInputMethod =
  (typeof UploadIntentInputMethod)[keyof typeof UploadIntentInputMethod];

export const UploadIntentInputMethod = {
  PUT: "PUT",
} as const;
