/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export interface UploadFileInputInput {
  /**
   * @minLength 1
   * @maxLength 255
   */
  fileName: string;
  /**
   * @minLength 1
   * @maxLength 120
   */
  mimeType: string;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum 0
   */
  sizeBytes?: number;
}
