/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { UploadIntentInputHeaders } from "./uploadIntentInputHeaders";
import type { UploadIntentInputMethod } from "./uploadIntentInputMethod";

export interface UploadIntentInput {
  uploadUrl: string;
  method: UploadIntentInputMethod;
  headers: UploadIntentInputHeaders;
}
