/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { UploadPresignResponseInputAssetType } from "./uploadPresignResponseInputAssetType";
import type { UploadPresignResponseInputHeaders } from "./uploadPresignResponseInputHeaders";
import type { UploadPresignResponseInputMethod } from "./uploadPresignResponseInputMethod";

export interface UploadPresignResponseInput {
  /** PUT your file here — signature is embedded */
  uploadUrl: string;
  /** Permanent public URL — store in resource fields */
  file_url: string;
  key: string;
  method: UploadPresignResponseInputMethod;
  /**
   * Presigned URL TTL in seconds
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  expiresIn: number;
  /** Include in the PUT request */
  headers: UploadPresignResponseInputHeaders;
  assetType: UploadPresignResponseInputAssetType;
  fileName: string;
}
