/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type UploadPresignResponseInputMethod =
  (typeof UploadPresignResponseInputMethod)[keyof typeof UploadPresignResponseInputMethod];

export const UploadPresignResponseInputMethod = {
  PUT: "PUT",
} as const;
