/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { I18nString } from "./i18nString";
import type { VariantAttrValue } from "./variantAttrValue";

export interface VariantAttr {
  attribute_id: string;
  attribute_name?: I18nString;
  value: VariantAttrValue;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order: number;
  highlighted: boolean;
}
