/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */

export type VariantAttrAttributeType =
  (typeof VariantAttrAttributeType)[keyof typeof VariantAttrAttributeType];

export const VariantAttrAttributeType = {
  TEXT: "TEXT",
  MATRIX: "MATRIX",
} as const;
