/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  Attribute,
  PatchApiAttributesIdBody,
  PostApiAttributesBody,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List all global technical attributes
 */
export const getApiAttributes = (signal?: AbortSignal) => {
  return orvalClient<Attribute[]>({
    url: `/api/attributes`,
    method: "GET",
    signal,
  });
};

export const getGetApiAttributesQueryKey = () => {
  return [`/api/attributes`] as const;
};

export const getGetApiAttributesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAttributes>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiAttributes>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiAttributesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiAttributes>>
  > = ({ signal }) => getApiAttributes(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAttributes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAttributesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAttributes>>
>;
export type GetApiAttributesQueryError = unknown;

export function useGetApiAttributes<
  TData = Awaited<ReturnType<typeof getApiAttributes>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAttributes>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAttributes>>,
          TError,
          Awaited<ReturnType<typeof getApiAttributes>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAttributes<
  TData = Awaited<ReturnType<typeof getApiAttributes>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAttributes>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAttributes>>,
          TError,
          Awaited<ReturnType<typeof getApiAttributes>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAttributes<
  TData = Awaited<ReturnType<typeof getApiAttributes>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAttributes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all global technical attributes
 */

export function useGetApiAttributes<
  TData = Awaited<ReturnType<typeof getApiAttributes>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAttributes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAttributesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a global attribute
 */
export const postApiAttributes = (
  postApiAttributesBody: PostApiAttributesBody,
  signal?: AbortSignal,
) => {
  return orvalClient<Attribute>({
    url: `/api/attributes`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiAttributesBody,
    signal,
  });
};

export const getPostApiAttributesQueryKey = (
  postApiAttributesBody?: PostApiAttributesBody,
) => {
  return ["POST", `/api/attributes`, postApiAttributesBody] as const;
};

export const getPostApiAttributesQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiAttributes>>,
  TError = unknown,
>(
  postApiAttributesBody: PostApiAttributesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAttributes>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPostApiAttributesQueryKey(postApiAttributesBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiAttributes>>
  > = ({ signal }) => postApiAttributes(postApiAttributesBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiAttributes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiAttributesQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiAttributes>>
>;
export type PostApiAttributesQueryError = unknown;

export function usePostApiAttributes<
  TData = Awaited<ReturnType<typeof postApiAttributes>>,
  TError = unknown,
>(
  postApiAttributesBody: PostApiAttributesBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAttributes>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAttributes>>,
          TError,
          Awaited<ReturnType<typeof postApiAttributes>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiAttributes<
  TData = Awaited<ReturnType<typeof postApiAttributes>>,
  TError = unknown,
>(
  postApiAttributesBody: PostApiAttributesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAttributes>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAttributes>>,
          TError,
          Awaited<ReturnType<typeof postApiAttributes>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiAttributes<
  TData = Awaited<ReturnType<typeof postApiAttributes>>,
  TError = unknown,
>(
  postApiAttributesBody: PostApiAttributesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAttributes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Create a global attribute
 */

export function usePostApiAttributes<
  TData = Awaited<ReturnType<typeof postApiAttributes>>,
  TError = unknown,
>(
  postApiAttributesBody: PostApiAttributesBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAttributes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiAttributesQueryOptions(
    postApiAttributesBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update an attribute
 */
export const patchApiAttributesId = (
  id: string,
  patchApiAttributesIdBody: PatchApiAttributesIdBody,
  signal?: AbortSignal,
) => {
  return orvalClient<Attribute>({
    url: `/api/attributes/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchApiAttributesIdBody,
    signal,
  });
};

export const getPatchApiAttributesIdQueryKey = (
  id: string,
  patchApiAttributesIdBody?: PatchApiAttributesIdBody,
) => {
  return ["PATCH", `/api/attributes/${id}`, patchApiAttributesIdBody] as const;
};

export const getPatchApiAttributesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof patchApiAttributesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiAttributesIdBody: PatchApiAttributesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiAttributesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPatchApiAttributesIdQueryKey(id, patchApiAttributesIdBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof patchApiAttributesId>>
  > = ({ signal }) =>
    patchApiAttributesId(id, patchApiAttributesIdBody, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof patchApiAttributesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatchApiAttributesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof patchApiAttributesId>>
>;
export type PatchApiAttributesIdQueryError = ApiErrorPayload;

export function usePatchApiAttributesId<
  TData = Awaited<ReturnType<typeof patchApiAttributesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiAttributesIdBody: PatchApiAttributesIdBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiAttributesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiAttributesId>>,
          TError,
          Awaited<ReturnType<typeof patchApiAttributesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiAttributesId<
  TData = Awaited<ReturnType<typeof patchApiAttributesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiAttributesIdBody: PatchApiAttributesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiAttributesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchApiAttributesId>>,
          TError,
          Awaited<ReturnType<typeof patchApiAttributesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePatchApiAttributesId<
  TData = Awaited<ReturnType<typeof patchApiAttributesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiAttributesIdBody: PatchApiAttributesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiAttributesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Update an attribute
 */

export function usePatchApiAttributesId<
  TData = Awaited<ReturnType<typeof patchApiAttributesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  patchApiAttributesIdBody: PatchApiAttributesIdBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof patchApiAttributesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPatchApiAttributesIdQueryOptions(
    id,
    patchApiAttributesIdBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete an attribute
 */
export const deleteApiAttributesId = (id: string, signal?: AbortSignal) => {
  return orvalClient<unknown>({
    url: `/api/attributes/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiAttributesIdQueryKey = (id: string) => {
  return ["DELETE", `/api/attributes/${id}`] as const;
};

export const getDeleteApiAttributesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiAttributesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiAttributesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDeleteApiAttributesIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiAttributesId>>
  > = ({ signal }) => deleteApiAttributesId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiAttributesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiAttributesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiAttributesId>>
>;
export type DeleteApiAttributesIdQueryError = ApiErrorPayload;

export function useDeleteApiAttributesId<
  TData = Awaited<ReturnType<typeof deleteApiAttributesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiAttributesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiAttributesId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiAttributesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiAttributesId<
  TData = Awaited<ReturnType<typeof deleteApiAttributesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiAttributesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiAttributesId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiAttributesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiAttributesId<
  TData = Awaited<ReturnType<typeof deleteApiAttributesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiAttributesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Delete an attribute
 */

export function useDeleteApiAttributesId<
  TData = Awaited<ReturnType<typeof deleteApiAttributesId>>,
  TError = ApiErrorPayload,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiAttributesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiAttributesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
