/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetApiPartnerLocationsParams,
  PartnerLocation,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary List partner locations
 */
export const getApiPartnerLocations = (
  params?: GetApiPartnerLocationsParams,
  signal?: AbortSignal,
) => {
  return orvalClient<PartnerLocation[]>({
    url: `/api/partner-locations`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiPartnerLocationsQueryKey = (
  params?: GetApiPartnerLocationsParams,
) => {
  return [`/api/partner-locations`, ...(params ? [params] : [])] as const;
};

export const getGetApiPartnerLocationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPartnerLocations>>,
  TError = unknown,
>(
  params?: GetApiPartnerLocationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPartnerLocations>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiPartnerLocationsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiPartnerLocations>>
  > = ({ signal }) => getApiPartnerLocations(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPartnerLocations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPartnerLocationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPartnerLocations>>
>;
export type GetApiPartnerLocationsQueryError = unknown;

export function useGetApiPartnerLocations<
  TData = Awaited<ReturnType<typeof getApiPartnerLocations>>,
  TError = unknown,
>(
  params: undefined | GetApiPartnerLocationsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPartnerLocations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPartnerLocations>>,
          TError,
          Awaited<ReturnType<typeof getApiPartnerLocations>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPartnerLocations<
  TData = Awaited<ReturnType<typeof getApiPartnerLocations>>,
  TError = unknown,
>(
  params?: GetApiPartnerLocationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPartnerLocations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPartnerLocations>>,
          TError,
          Awaited<ReturnType<typeof getApiPartnerLocations>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPartnerLocations<
  TData = Awaited<ReturnType<typeof getApiPartnerLocations>>,
  TError = unknown,
>(
  params?: GetApiPartnerLocationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPartnerLocations>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List partner locations
 */

export function useGetApiPartnerLocations<
  TData = Awaited<ReturnType<typeof getApiPartnerLocations>>,
  TError = unknown,
>(
  params?: GetApiPartnerLocationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPartnerLocations>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPartnerLocationsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
