/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProductsParams } from "../../model/getApiProductsParams";

import type { GetApiProductsSlug200 } from "../../model/getApiProductsSlug200";

import type { GetApiProductsSlugParams } from "../../model/getApiProductsSlugParams";

import type { ProductCatalogResponse } from "../../model/productCatalogResponse";

import { serverOrvalClient } from "../../orval-server";

/**
 * @summary List products
 */
export const getApiProducts = (params?: GetApiProductsParams) => {
  return serverOrvalClient<ProductCatalogResponse>({
    url: `/api/products`,
    method: "GET",
    params,
  });
};
/**
 * @summary Get product
 */
export const getApiProductsSlug = (
  slug: string,
  params?: GetApiProductsSlugParams,
) => {
  return serverOrvalClient<GetApiProductsSlug200>({
    url: `/api/products/${slug}`,
    method: "GET",
    params,
  });
};
export type GetApiProductsResult = NonNullable<
  Awaited<ReturnType<typeof getApiProducts>>
>;
export type GetApiProductsSlugResult = NonNullable<
  Awaited<ReturnType<typeof getApiProductsSlug>>
>;
