/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AccessTokenResponse,
  AdminUser,
  ApiErrorPayload,
  LogoutResponse,
  PostApiAuthLoginBody,
  PostApiAuthRefreshBody,
  TokensResponse,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary Get current authenticated user
 */
export const getApiAuthMe = (signal?: AbortSignal) => {
  return orvalClient<AdminUser>({ url: `/api/auth/me`, method: "GET", signal });
};

export const getGetApiAuthMeQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetApiAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = ApiErrorPayload,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthMe>>> = ({
    signal,
  }) => getApiAuthMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAuthMe>>
>;
export type GetApiAuthMeQueryError = ApiErrorPayload;

export function useGetApiAuthMe<
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = ApiErrorPayload,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthMe<
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = ApiErrorPayload,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthMe<
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = ApiErrorPayload,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current authenticated user
 */

export function useGetApiAuthMe<
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = ApiErrorPayload,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAuthMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Authenticate and receive tokens
 */
export const postApiAuthLogin = (
  postApiAuthLoginBody: PostApiAuthLoginBody,
  signal?: AbortSignal,
) => {
  return orvalClient<TokensResponse>({
    url: `/api/auth/login`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiAuthLoginBody,
    signal,
  });
};

export const getPostApiAuthLoginQueryKey = (
  postApiAuthLoginBody?: PostApiAuthLoginBody,
) => {
  return ["POST", `/api/auth/login`, postApiAuthLoginBody] as const;
};

export const getPostApiAuthLoginQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError = ApiErrorPayload,
>(
  postApiAuthLoginBody: PostApiAuthLoginBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPostApiAuthLoginQueryKey(postApiAuthLoginBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiAuthLogin>>
  > = ({ signal }) => postApiAuthLogin(postApiAuthLoginBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiAuthLogin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiAuthLoginQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthLogin>>
>;
export type PostApiAuthLoginQueryError = ApiErrorPayload;

export function usePostApiAuthLogin<
  TData = Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError = ApiErrorPayload,
>(
  postApiAuthLoginBody: PostApiAuthLoginBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAuthLogin>>,
          TError,
          Awaited<ReturnType<typeof postApiAuthLogin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiAuthLogin<
  TData = Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError = ApiErrorPayload,
>(
  postApiAuthLoginBody: PostApiAuthLoginBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAuthLogin>>,
          TError,
          Awaited<ReturnType<typeof postApiAuthLogin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiAuthLogin<
  TData = Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError = ApiErrorPayload,
>(
  postApiAuthLoginBody: PostApiAuthLoginBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Authenticate and receive tokens
 */

export function usePostApiAuthLogin<
  TData = Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError = ApiErrorPayload,
>(
  postApiAuthLoginBody: PostApiAuthLoginBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiAuthLoginQueryOptions(
    postApiAuthLoginBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Refresh access token using a refresh token
 */
export const postApiAuthRefresh = (
  postApiAuthRefreshBody: PostApiAuthRefreshBody,
  signal?: AbortSignal,
) => {
  return orvalClient<AccessTokenResponse>({
    url: `/api/auth/refresh`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiAuthRefreshBody,
    signal,
  });
};

export const getPostApiAuthRefreshQueryKey = (
  postApiAuthRefreshBody?: PostApiAuthRefreshBody,
) => {
  return ["POST", `/api/auth/refresh`, postApiAuthRefreshBody] as const;
};

export const getPostApiAuthRefreshQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiAuthRefresh>>,
  TError = ApiErrorPayload,
>(
  postApiAuthRefreshBody: PostApiAuthRefreshBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAuthRefresh>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPostApiAuthRefreshQueryKey(postApiAuthRefreshBody);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postApiAuthRefresh>>
  > = ({ signal }) => postApiAuthRefresh(postApiAuthRefreshBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiAuthRefresh>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiAuthRefreshQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthRefresh>>
>;
export type PostApiAuthRefreshQueryError = ApiErrorPayload;

export function usePostApiAuthRefresh<
  TData = Awaited<ReturnType<typeof postApiAuthRefresh>>,
  TError = ApiErrorPayload,
>(
  postApiAuthRefreshBody: PostApiAuthRefreshBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAuthRefresh>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAuthRefresh>>,
          TError,
          Awaited<ReturnType<typeof postApiAuthRefresh>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiAuthRefresh<
  TData = Awaited<ReturnType<typeof postApiAuthRefresh>>,
  TError = ApiErrorPayload,
>(
  postApiAuthRefreshBody: PostApiAuthRefreshBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAuthRefresh>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAuthRefresh>>,
          TError,
          Awaited<ReturnType<typeof postApiAuthRefresh>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiAuthRefresh<
  TData = Awaited<ReturnType<typeof postApiAuthRefresh>>,
  TError = ApiErrorPayload,
>(
  postApiAuthRefreshBody: PostApiAuthRefreshBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAuthRefresh>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Refresh access token using a refresh token
 */

export function usePostApiAuthRefresh<
  TData = Awaited<ReturnType<typeof postApiAuthRefresh>>,
  TError = ApiErrorPayload,
>(
  postApiAuthRefreshBody: PostApiAuthRefreshBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postApiAuthRefresh>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiAuthRefreshQueryOptions(
    postApiAuthRefreshBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Logout (stateless — discard tokens client-side)
 */
export const deleteApiAuthLogout = (signal?: AbortSignal) => {
  return orvalClient<LogoutResponse>({
    url: `/api/auth/logout`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteApiAuthLogoutQueryKey = () => {
  return ["DELETE", `/api/auth/logout`] as const;
};

export const getDeleteApiAuthLogoutQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteApiAuthLogout>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof deleteApiAuthLogout>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDeleteApiAuthLogoutQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof deleteApiAuthLogout>>
  > = ({ signal }) => deleteApiAuthLogout(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteApiAuthLogout>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiAuthLogoutQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiAuthLogout>>
>;
export type DeleteApiAuthLogoutQueryError = unknown;

export function useDeleteApiAuthLogout<
  TData = Awaited<ReturnType<typeof deleteApiAuthLogout>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiAuthLogout>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiAuthLogout>>,
          TError,
          Awaited<ReturnType<typeof deleteApiAuthLogout>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiAuthLogout<
  TData = Awaited<ReturnType<typeof deleteApiAuthLogout>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiAuthLogout>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiAuthLogout>>,
          TError,
          Awaited<ReturnType<typeof deleteApiAuthLogout>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeleteApiAuthLogout<
  TData = Awaited<ReturnType<typeof deleteApiAuthLogout>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiAuthLogout>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Logout (stateless — discard tokens client-side)
 */

export function useDeleteApiAuthLogout<
  TData = Awaited<ReturnType<typeof deleteApiAuthLogout>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof deleteApiAuthLogout>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeleteApiAuthLogoutQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
