/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPartnerLocationsParams } from "../../model/getApiPartnerLocationsParams";

import type { PartnerLocation } from "../../model/partnerLocation";

import { serverOrvalClient } from "../../orval-server";

/**
 * @summary List partner locations
 */
export const getApiPartnerLocations = (
  params?: GetApiPartnerLocationsParams,
) => {
  return serverOrvalClient<PartnerLocation[]>({
    url: `/api/partner-locations`,
    method: "GET",
    params,
  });
};
export type GetApiPartnerLocationsResult = NonNullable<
  Awaited<ReturnType<typeof getApiPartnerLocations>>
>;
