/**
 * Stetsom API — auto-generated by Orval.
 * Do not edit manually. Run `pnpm api:generate` to regenerate.
 *
 * Usage (Client Component):
 *   import { useGetApiBanners, usePostApiBanners } from "@/api/stetsom"
 *
 * Usage (Server Component / Server Action):
 *   import { serverOrvalClient } from "@/api/stetsom/orval-server"
 */

// ── Models (TypeScript types) ─────────────────────────────────────────────────
export * from "./model";

// ── React Query hooks — CMS ───────────────────────────────────────────────────
export * from "./endpoints/attributes/attributes";
export * from "./endpoints/audit/audit";
export * from "./endpoints/auth/auth";
export * from "./endpoints/banners/banners";
export * from "./endpoints/categories/categories";
export * from "./endpoints/config/config";
export * from "./endpoints/contact/contact";
export * from "./endpoints/dashboard/dashboard";
export * from "./endpoints/library/library";
export * from "./endpoints/messages/messages";
export * from "./endpoints/pages/pages";
export * from "./endpoints/products/products";
export * from "./endpoints/representatives/representatives";
export * from "./endpoints/service-centers/service-centers";
export * from "./endpoints/templates/templates";
export * from "./endpoints/upload/upload";
export * from "./endpoints/users/users";

// ── React Query hooks — Public Site ──────────────────────────────────────────
export * from "./endpoints/banners-public/banners-public";
export * from "./endpoints/categories-public/categories-public";
export * from "./endpoints/pages-public/pages-public";
export * from "./endpoints/products-public/products-public";
export * from "./endpoints/representatives-public/representatives-public";
export * from "./endpoints/service-centers-public/service-centers-public";

// ── Error class ───────────────────────────────────────────────────────────────
export { OrvalApiError } from "./orval-client";
