/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiLegalPagesPublicParams } from "../../model/getApiLegalPagesPublicParams";

import type { GetApiLegalPagesPublicSlugParams } from "../../model/getApiLegalPagesPublicSlugParams";

import type { PublicLegalPage } from "../../model/publicLegalPage";

import type { PublicLegalPageListItem } from "../../model/publicLegalPageListItem";

import { serverOrvalClient } from "../../orval-server";

/**
 * @summary List published legal pages (footer)
 */
export const getApiLegalPagesPublic = (
  params?: GetApiLegalPagesPublicParams,
) => {
  return serverOrvalClient<PublicLegalPageListItem[]>({
    url: `/api/legal-pages/public`,
    method: "GET",
    params,
  });
};
/**
 * @summary Get a published legal page by slug
 */
export const getApiLegalPagesPublicSlug = (
  slug: string,
  params?: GetApiLegalPagesPublicSlugParams,
) => {
  return serverOrvalClient<PublicLegalPage>({
    url: `/api/legal-pages/public/${slug}`,
    method: "GET",
    params,
  });
};
export type GetApiLegalPagesPublicResult = NonNullable<
  Awaited<ReturnType<typeof getApiLegalPagesPublic>>
>;
export type GetApiLegalPagesPublicSlugResult = NonNullable<
  Awaited<ReturnType<typeof getApiLegalPagesPublicSlug>>
>;
