/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBannersActiveParams } from "../../model/getApiBannersActiveParams";

import type { HeroBannerSlidesPayload } from "../../model/heroBannerSlidesPayload";

import { serverOrvalClient } from "../../orval-server";

/**
 * @summary List active banners
 */
export const getApiBannersActive = (params?: GetApiBannersActiveParams) => {
  return serverOrvalClient<HeroBannerSlidesPayload>({
    url: `/api/banners/active`,
    method: "GET",
    params,
  });
};
export type GetApiBannersActiveResult = NonNullable<
  Awaited<ReturnType<typeof getApiBannersActive>>
>;
