/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Stetsom API
 * API documentation for Stetsom
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorPayload,
  PostApiContact200,
  PostApiContactBody,
} from "../../model";

import { orvalClient } from "../../orval-client";

/**
 * @summary Submissão do formulário de contato
 */
export const postApiContact = (
  postApiContactBody: PostApiContactBody,
  signal?: AbortSignal,
) => {
  return orvalClient<PostApiContact200>({
    url: `/api/contact/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiContactBody,
    signal,
  });
};

export const getPostApiContactQueryKey = (
  postApiContactBody?: PostApiContactBody,
) => {
  return ["POST", `/api/contact/`, postApiContactBody] as const;
};

export const getPostApiContactQueryOptions = <
  TData = Awaited<ReturnType<typeof postApiContact>>,
  TError = ApiErrorPayload,
>(
  postApiContactBody: PostApiContactBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiContact>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPostApiContactQueryKey(postApiContactBody);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiContact>>> = ({
    signal,
  }) => postApiContact(postApiContactBody, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postApiContact>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiContactQueryResult = NonNullable<
  Awaited<ReturnType<typeof postApiContact>>
>;
export type PostApiContactQueryError = ApiErrorPayload;

export function usePostApiContact<
  TData = Awaited<ReturnType<typeof postApiContact>>,
  TError = ApiErrorPayload,
>(
  postApiContactBody: PostApiContactBody,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiContact>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiContact>>,
          TError,
          Awaited<ReturnType<typeof postApiContact>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiContact<
  TData = Awaited<ReturnType<typeof postApiContact>>,
  TError = ApiErrorPayload,
>(
  postApiContactBody: PostApiContactBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiContact>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiContact>>,
          TError,
          Awaited<ReturnType<typeof postApiContact>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostApiContact<
  TData = Awaited<ReturnType<typeof postApiContact>>,
  TError = ApiErrorPayload,
>(
  postApiContactBody: PostApiContactBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiContact>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Submissão do formulário de contato
 */

export function usePostApiContact<
  TData = Awaited<ReturnType<typeof postApiContact>>,
  TError = ApiErrorPayload,
>(
  postApiContactBody: PostApiContactBody,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postApiContact>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostApiContactQueryOptions(
    postApiContactBody,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
