"use client";

import { cn } from "@/lib/utils";
import { Bounds, Html, OrbitControls, useGLTF } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { Suspense, useMemo, type CSSProperties } from "react";
import { LinearFilter, Mesh, type Object3D, type Texture } from "three";

/** Standard three.js material texture slots that may carry mipmaps. */
const TEXTURE_KEYS = [
  "map",
  "normalMap",
  "roughnessMap",
  "metalnessMap",
  "emissiveMap",
  "aoMap",
  "bumpMap",
  "displacementMap",
  "alphaMap",
  "lightMap",
  "specularMap",
  "envMap",
] as const;

/**
 * Disable mipmaps on every texture in the scene. Mipmaps are generated by
 * default; turning them off requires also switching the min filter away from a
 * mipmap-based one (the default `LinearMipmapLinearFilter` needs mipmaps).
 */
function disableMipmaps(root: Object3D): void {
  root.traverse((obj) => {
    if (!(obj instanceof Mesh)) return;
    const materials = Array.isArray(obj.material)
      ? obj.material
      : [obj.material];
    for (const material of materials) {
      if (!material) continue;
      const slots = material as unknown as Record<string, unknown>;
      for (const key of TEXTURE_KEYS) {
        const tex = slots[key] as Texture | null | undefined;
        if (!tex?.isTexture) continue;
        tex.generateMipmaps = false;
        tex.minFilter = LinearFilter;
        tex.needsUpdate = true;
      }
    }
  });
}

interface Model3DViewerProps {
  /** Public URL of the .glb asset. */
  url: string;
  /** Optional background color (hex). Falls back to brand-dark when absent. */
  backgroundColor?: string;
  /** Optional background image URL, drawn over the color (cover, centered). */
  backgroundImage?: string;
  /** Label shown while the model streams in. */
  loadingLabel?: string;
  className?: string;
}

function Model({ url }: { url: string }) {
  const { scene } = useGLTF(url);
  // Clone so the cached scene isn't mutated by Bounds/OrbitControls transforms.
  const cloned = useMemo(() => {
    const copy = scene.clone();
    disableMipmaps(copy);
    return copy;
  }, [scene]);
  return <primitive object={cloned} />;
}

/**
 * Interactive GLB viewer for MODEL3D product blocks. Drag to orbit (rotation
 * only — zoom and pan are disabled by design). Rendered client-side only
 * (imported via `next/dynamic` with `ssr: false`) to keep three.js off the
 * server bundle and out of SSR (WebGL needs the browser). Used both on the
 * public product page and as a live preview in the CMS block editor.
 */
export function Model3DViewer({
  url,
  backgroundColor,
  backgroundImage,
  loadingLabel = "Carregando…",
  className,
}: Model3DViewerProps) {
  // The Canvas renders transparent (alpha) so the DOM background shows through.
  // Color is the base layer; the image is drawn over it (cover, centered).
  const style: CSSProperties = {};
  if (backgroundColor) style.backgroundColor = backgroundColor;
  if (backgroundImage) {
    style.backgroundImage = `url(${backgroundImage})`;
    style.backgroundSize = "cover";
    style.backgroundPosition = "center";
    style.backgroundRepeat = "no-repeat";
  }

  return (
    <div
      className={cn(
        "h-full w-full overflow-hidden",
        !backgroundColor && !backgroundImage && "bg-brand-dark",
        className,
      )}
      style={style}
    >
      <Canvas camera={{ position: [0, 2.5, 5], fov: 50 }} dpr={[1, 2]}>
        <ambientLight intensity={4} />
        <directionalLight position={[5, 5, 5]} intensity={5} />
        <directionalLight position={[-5, -2, -5]} intensity={5} />
        <Suspense
          fallback={
            <Html center>
              <span className="aspect-video w-full text-sm whitespace-nowrap text-text-subtle-dark">
                {loadingLabel}
              </span>
            </Html>
          }
        >
          <Bounds fit clip observe margin={1.2}>
            <Model url={url} />
          </Bounds>
        </Suspense>
        <OrbitControls makeDefault enableZoom={false} enablePan={false} />
      </Canvas>
    </div>
  );
}
